# Kenya Financial Inclusion Analysis 2024
## County, Regional, and National Financial Inclusion Findings

This section combines geographic, demographic, financial access, financial health, and vulnerability indicators to produce county, regional, and national level summaries. It provides a consolidated view of how financial inclusion is distributed across the country, highlighting areas where access to financial services is widespread as well as regions where exclusion remains concentrated. The results also help identify socioeconomic and geographic disparities in financial inclusion, providing evidence for more targeted policy interventions and financial product design aimed at improving inclusion outcomes.


In [1]:
# Shared setup keeps credentials, paths, and database access consistent across the analysis.
from pathlib import Path
import os

import pandas as pd
from sqlalchemy import create_engine, text

# Credential loading keeps local secrets out of versioned analysis files.
# Fallback loading keeps the connection usable across different local kernels.
try:
    from dotenv import load_dotenv
except ImportError:
    def load_dotenv(dotenv_path):
        dotenv_path = Path(dotenv_path)
        if not dotenv_path.exists():
            return False
        for line in dotenv_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))
        return True

# Absolute paths prevent exports from depending on the active working directory.
PROJECT_ROOT = Path(r"C:\Portfolio\FinancialInclusion2024")
DATA_DIR = PROJECT_ROOT / "data"
OUTPUT_DIR = PROJECT_ROOT / "outputs"
FIGURE_DIR = OUTPUT_DIR / "figures"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
FIGURE_DIR.mkdir(parents=True, exist_ok=True)

# The local .env file keeps the database password outside analysis outputs.
# Git ignores .env so credentials remain local to the analyst machine.
load_dotenv(PROJECT_ROOT / ".env")
DB_PASSWORD = os.getenv("DB_PASSWORD")

if not DB_PASSWORD:
    raise ValueError(f"DB_PASSWORD is missing. Add it to {PROJECT_ROOT / '.env'} before running this notebook.")

DATABASE_URL = f"postgresql+psycopg2://postgres:{DB_PASSWORD}@localhost:5432/finaccess_db"
engine = create_engine(DATABASE_URL)

# Database validation prevents downstream analysis from using the wrong connection.
pd.read_sql("SELECT current_database() AS database_name, current_user AS user_name;", engine)


,database_name,user_name
0,finaccess_db,postgres


## Section 4: Geography and Reference Data

County and access-strand reference data convert coded survey values into clear geographic and financial inclusion categories. These standardized labels ensure that analytical results are interpretable and consistent across reports. They also make it easier to translate findings into practical insights that can guide policy decisions, programme design, and financial product development at both county and national levels.


### County and Access Reference Tables

The reference tables standardise county names, regions, and access-strand labels. This ensures that county and access categories are reported consistently across the analysis.


In [2]:
from sqlalchemy import text

# Drop dependent views and materialized view before recreating the lookup table
drop_query = """
DROP MATERIALIZED VIEW IF EXISTS county_scorecard CASCADE;
DROP VIEW IF EXISTS financial_exclusion_analysis CASCADE;
DROP VIEW IF EXISTS gender_financial_gap CASCADE;
DROP VIEW IF EXISTS county_financial_summary CASCADE;
DROP TABLE IF EXISTS county_reference CASCADE;
DROP TABLE IF EXISTS access_strand_reference CASCADE;
"""

with engine.connect() as conn:
    conn.execute(text(drop_query))
    conn.commit()

print("Dependent objects dropped. Ready to recreate lookup tables and views.")

Dependent objects dropped. Ready to recreate lookup tables and views.


In [3]:
# Reference tables standardise county, region, and access-strand labels for reporting.
county_reference_data = [
    {"county_code": 1, "county_name": "Mombasa", "region": "Coast"},
    {"county_code": 2, "county_name": "Kwale", "region": "Coast"},
    {"county_code": 3, "county_name": "Kilifi", "region": "Coast"},
    {"county_code": 4, "county_name": "Tana River", "region": "Coast"},
    {"county_code": 5, "county_name": "Lamu", "region": "Coast"},
    {"county_code": 6, "county_name": "Taita Taveta", "region": "Coast"},
    {"county_code": 7, "county_name": "Garissa", "region": "North Eastern"},
    {"county_code": 8, "county_name": "Wajir", "region": "North Eastern"},
    {"county_code": 9, "county_name": "Mandera", "region": "North Eastern"},
    {"county_code": 10, "county_name": "Marsabit", "region": "Eastern"},
    {"county_code": 11, "county_name": "Isiolo", "region": "Eastern"},
    {"county_code": 12, "county_name": "Meru", "region": "Eastern"},
    {"county_code": 13, "county_name": "Tharaka-Nithi", "region": "Eastern"},
    {"county_code": 14, "county_name": "Embu", "region": "Eastern"},
    {"county_code": 15, "county_name": "Kitui", "region": "Eastern"},
    {"county_code": 16, "county_name": "Machakos", "region": "Eastern"},
    {"county_code": 17, "county_name": "Makueni", "region": "Eastern"},
    {"county_code": 18, "county_name": "Nyandarua", "region": "Central"},
    {"county_code": 19, "county_name": "Nyeri", "region": "Central"},
    {"county_code": 20, "county_name": "Kirinyaga", "region": "Central"},
    {"county_code": 21, "county_name": "Murang'a", "region": "Central"},
    {"county_code": 22, "county_name": "Kiambu", "region": "Central"},
    {"county_code": 23, "county_name": "Turkana", "region": "Rift Valley"},
    {"county_code": 24, "county_name": "West Pokot", "region": "Rift Valley"},
    {"county_code": 25, "county_name": "Samburu", "region": "Rift Valley"},
    {"county_code": 26, "county_name": "Trans Nzoia", "region": "Rift Valley"},
    {"county_code": 27, "county_name": "Uasin Gishu", "region": "Rift Valley"},
    {"county_code": 28, "county_name": "Elgeyo-Marakwet", "region": "Rift Valley"},
    {"county_code": 29, "county_name": "Nandi", "region": "Rift Valley"},
    {"county_code": 30, "county_name": "Baringo", "region": "Rift Valley"},
    {"county_code": 31, "county_name": "Laikipia", "region": "Rift Valley"},
    {"county_code": 32, "county_name": "Nakuru", "region": "Rift Valley"},
    {"county_code": 33, "county_name": "Narok", "region": "Rift Valley"},
    {"county_code": 34, "county_name": "Kajiado", "region": "Rift Valley"},
    {"county_code": 35, "county_name": "Kericho", "region": "Rift Valley"},
    {"county_code": 36, "county_name": "Bomet", "region": "Rift Valley"},
    {"county_code": 37, "county_name": "Kakamega", "region": "Western"},
    {"county_code": 38, "county_name": "Vihiga", "region": "Western"},
    {"county_code": 39, "county_name": "Bungoma", "region": "Western"},
    {"county_code": 40, "county_name": "Busia", "region": "Western"},
    {"county_code": 41, "county_name": "Siaya", "region": "Nyanza"},
    {"county_code": 42, "county_name": "Kisumu", "region": "Nyanza"},
    {"county_code": 43, "county_name": "Homa Bay", "region": "Nyanza"},
    {"county_code": 44, "county_name": "Migori", "region": "Nyanza"},
    {"county_code": 45, "county_name": "Kisii", "region": "Nyanza"},
    {"county_code": 46, "county_name": "Nyamira", "region": "Nyanza"},
    {"county_code": 47, "county_name": "Nairobi", "region": "Nairobi"},
]

access_strand_reference_data = [
    {"strand_code": 1, "strand_label": "Formally Included"},
    {"strand_code": 2, "strand_label": "Informally Served"},
    {"strand_code": 3, "strand_label": "Financially Excluded"},
    {"strand_code": 4, "strand_label": "Other Financial Service"},
]

county_reference = pd.DataFrame(county_reference_data)
access_strand_reference = pd.DataFrame(access_strand_reference_data)

county_reference.to_sql("county_reference", engine, if_exists="replace", index=False)
access_strand_reference.to_sql("access_strand_reference", engine, if_exists="replace", index=False)

query = """
SELECT 'county_reference' AS table_name, COUNT(*) AS row_count FROM county_reference
UNION ALL
SELECT 'access_strand_reference' AS table_name, COUNT(*) AS row_count FROM access_strand_reference;
"""

df_lookup_table_check = pd.read_sql(query, engine)
df_lookup_table_check

,table_name,row_count
0,county_reference,47
1,access_strand_reference,4


The lookup-table check shows `47` rows in `county_reference` and `4` rows in `access_strand_reference`. This confirms that the reference tables are ready for joins.

These lookup tables add the geographic and categorical context that raw survey codes do not provide on their own.


### 1. County Inclusion by Name and Region

County names and regions make the inclusion rates easier to interpret for stakeholders. The output links local access outcomes to the geography where policy and product decisions are made.


In [4]:
# County labels connect inclusion rates to actionable geographic markets.
query = """
SELECT
    cr.county_code,
    cr.county_name,
    cr.region,
    COUNT(*) AS respondent_count,
    ROUND(AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS mobile_money_use_rate_percent,
    ROUND(AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS bank_use_rate_percent,
    ROUND(AVG(CASE WHEN fm.bank_use = 1 AND fm.mobile_money_use = 1 THEN 1.0 ELSE 0.0 END) * 100, 2) AS fully_included_rate_percent
FROM finaccess_master fm
INNER JOIN county_reference cr
    ON CAST(fm.county AS INTEGER) = cr.county_code
GROUP BY cr.county_code, cr.county_name, cr.region
ORDER BY fully_included_rate_percent DESC;
"""

df_county_joined_rates = pd.read_sql(query, engine)
df_county_joined_rates

,county_code,county_name,region,respondent_count,mobile_money_use_rate_percent,bank_use_rate_percent,fully_included_rate_percent
0,47,Nairobi,Nairobi,622,92.93,72.99,72.67
1,22,Kiambu,Central,541,86.11,66.98,64.88
2,27,Uasin Gishu,Rift Valley,551,83.48,61.16,59.89
3,19,Nyeri,Central,457,89.93,59.30,58.21
4,29,Nandi,Rift Valley,475,81.68,59.58,56.84
5,34,Kajiado,Rift Valley,412,81.07,56.07,55.83
6,6,Taita Taveta,Coast,394,86.29,54.57,54.06
7,28,Elgeyo-Marakwet,Rift Valley,426,83.80,53.99,53.76
8,26,Trans Nzoia,Rift Valley,162,74.69,53.70,53.70
9,14,Embu,Eastern,478,87.03,54.18,53.35


The joined result shows clear geographic variation in financial inclusion. Nairobi has the highest simplified fully included rate among counties shown in the validation run, at `72.67` percent, with mobile money use at `92.93` percent and bank use at `72.99` percent. Kiambu, Uasin Gishu, Nyeri, and Nandi also appear near the top by the simplified bank-and-mobile inclusion measure.

At the lower end, counties such as West Pokot, Turkana, Baringo, Narok, and parts of the Coast and North Eastern regions show lower combined bank-and-mobile inclusion. This matters for NGOs and development organisations because geographic exclusion often reflects infrastructure, distance, livelihoods, income stability, agent networks, and trust in formal services.


### 2. County-Code Coverage

County-code coverage confirms whether all respondent records can be assigned to a county name and region. Complete coverage is necessary for reliable geographic reporting.


In [5]:
# County-code coverage prevents records from dropping out of geographic reporting.
query = """
SELECT
    CASE
        WHEN cr.county_code IS NULL THEN 'Unmatched county code'
        ELSE 'Matched county code'
    END AS join_status,
    COUNT(*) AS respondent_count,
    MIN(CAST(fm.county AS INTEGER)) AS min_county_code,
    MAX(CAST(fm.county AS INTEGER)) AS max_county_code
FROM finaccess_master fm
LEFT JOIN county_reference cr
    ON CAST(fm.county AS INTEGER) = cr.county_code
GROUP BY join_status
ORDER BY join_status;
"""

df_county_join_validation = pd.read_sql(query, engine)
df_county_join_validation

,join_status,respondent_count,min_county_code,max_county_code
0,Matched county code,20871,1,47


The result confirms that all `20,871` respondent records match a county code in `county_reference`. The matched county codes range from `1` to `47`, and there are no unmatched county-code records.

This is an important join-quality result. It means county names and regional labels can be safely attached to every respondent without dropping records. For fintechs and NGOs, this supports reliable geographic segmentation across the full survey base.


### 3. Regional Financial Behaviour

Regional summaries show whether mobile money, banking, savings, and loan usage differ across Kenya. These differences can guide regional targeting by fintechs, NGOs, and government programmes.


In [6]:
# Regional rates reveal market differences behind national averages.
query = """
SELECT
    cr.region,
    COUNT(*) AS respondent_count,
    ROUND(AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS mobile_money_use_rate_percent,
    ROUND(AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS bank_use_rate_percent,
    ROUND(AVG(CASE WHEN fm."Savings_usage" = 1 THEN 1.0 WHEN fm."Savings_usage" IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS savings_usage_rate_percent,
    ROUND(AVG(CASE WHEN fm."Loan_usage" = 1 THEN 1.0 WHEN fm."Loan_usage" IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS loan_usage_rate_percent
FROM finaccess_master fm
INNER JOIN county_reference cr
    ON CAST(fm.county AS INTEGER) = cr.county_code
GROUP BY cr.region
ORDER BY mobile_money_use_rate_percent DESC;
"""

df_region_usage_rates = pd.read_sql(query, engine)
df_region_usage_rates

,region,respondent_count,mobile_money_use_rate_percent,bank_use_rate_percent,savings_usage_rate_percent,loan_usage_rate_percent
0,Nairobi,622,92.93,72.99,87.14,63.83
1,Central,2451,84.82,55.61,69.36,66.71
2,Eastern,3598,81.24,46.36,65.29,65.79
3,North Eastern,1114,80.97,20.38,24.87,43.27
4,Coast,2320,78.81,39.88,48.49,52.67
5,Nyanza,2974,77.67,42.70,63.38,60.39
6,Rift Valley,5836,75.32,46.65,67.91,61.22
7,Western,1956,71.97,44.55,71.68,66.62


The regional result shows Nairobi as the strongest region on mobile money use and bank use, with `92.93` percent mobile money use and `72.99` percent bank use. Central follows with high mobile money use at `84.82` percent and bank use at `55.61` percent. North Eastern has high mobile money use at `80.97` percent but much lower bank use at `20.38` percent and savings usage at `24.87` percent.

This reveals that mobile money penetration can be strong even where bank and savings usage are weaker. For fintechs, North Eastern may require mobile-first products that do not assume strong bank integration. For NGOs and development organisations, low bank and savings usage may point to opportunities for financial capability, agent network strengthening, appropriate savings products, and trust-building. Western shows lower mobile money use at `71.97` percent but relatively strong savings usage at `71.68` percent, suggesting that different financial behaviours do not always move together.


### 4. Access Strand Labels

Access-strand labels translate coded categories into terms that can be used in reports and stakeholder discussions. This supports clearer interpretation of formal inclusion, informal service use, exclusion, and other pathways.


In [7]:
# Access-strand labels make coded inclusion categories usable for stakeholder reporting.
query = """
SELECT
    CAST(fm."Access_Strand" AS INTEGER) AS raw_access_strand_code,
    asr.strand_code AS reference_strand_code,
    asr.strand_label,
    COUNT(*) AS respondent_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM finaccess_master), 2) AS sample_share_percent
FROM finaccess_master fm
INNER JOIN access_strand_reference asr
    ON CAST(fm."Access_Strand" AS INTEGER) = asr.strand_code
GROUP BY raw_access_strand_code, asr.strand_code, asr.strand_label
ORDER BY raw_access_strand_code;
"""

df_access_strand_decoded = pd.read_sql(query, engine)
df_access_strand_decoded

,raw_access_strand_code,reference_strand_code,strand_label,respondent_count,sample_share_percent
0,1,1,Formally Included,187,0.90
1,2,2,Informally Served,446,2.14
2,3,3,Financially Excluded,11,0.05


The decoded result translates numeric access strand codes into readable categories such as `Formally Included`, `Informally Served`, `Financially Excluded`, and `Other Financial Service`. The exact counts should be reviewed after running the cell because they depend on the coded values currently stored in `"Access_Strand"`.

This result should still be interpreted with care because coded survey variables should always be validated against the official FinAccess metadata before publication.


### 5. Integrated Respondent Profile

Combining demographics, financial indicators, and county reference data creates a richer respondent-level view. This supports deeper segmentation when questions require variables from multiple source tables.


In [8]:
# Integrated respondent profiles support segmentation across demographics, geography, and access.
query = """
SELECT
    p1.interview__key,
    CAST(p1.county AS INTEGER) AS county_code,
    cr.county_name,
    cr.region,
    p1."Sex",
    p1."Age",
    p3b."Education",
    p3b."Marital",
    p3b.mobile_money_use,
    p3b.bank_use,
    p3b."Access_Strand",
    p3b."Overall_Access_fnl",
    p3b.finhealth_fnl,
    p3b.vul_index_fnl
FROM finaccess_part1 p1
INNER JOIN finaccess_part3b p3b
    ON p1.interview__key = p3b.interview__key
INNER JOIN county_reference cr
    ON CAST(p1.county AS INTEGER) = cr.county_code
ORDER BY p1.interview__key
LIMIT 20;
"""

df_three_table_join = pd.read_sql(query, engine)
df_three_table_join

,interview__key,county_code,county_name,region,Sex,Age,Education,Marital,mobile_money_use,bank_use,Access_Strand,Overall_Access_fnl,finhealth_fnl,vul_index_fnl
0,00-00-18-74,27,Uasin Gishu,Rift Valley,1.0,4.0,3.0,4.0,1.0,1.0,0.0,1.0,0.0,3.0
1,00-00-59-38,13,Tharaka-Nithi,Eastern,2.0,5.0,2.0,4.0,2.0,3.0,0.0,2.0,0.0,1.0
2,00-01-02-96,36,Bomet,Rift Valley,1.0,2.0,3.0,1.0,1.0,1.0,0.0,1.0,0.0,3.0
3,00-01-21-44,11,Isiolo,Eastern,1.0,6.0,1.0,4.0,1.0,3.0,0.0,1.0,0.0,1.0
4,00-01-36-47,46,Nyamira,Nyanza,2.0,3.0,2.0,4.0,1.0,1.0,0.0,1.0,0.0,3.0
5,00-01-41-64,34,Kajiado,Rift Valley,1.0,3.0,4.0,4.0,1.0,1.0,0.0,1.0,0.0,2.0
6,00-01-81-79,36,Bomet,Rift Valley,2.0,3.0,4.0,4.0,1.0,1.0,0.0,1.0,1.0,3.0
7,00-02-87-76,46,Nyamira,Nyanza,1.0,6.0,3.0,4.0,1.0,1.0,0.0,1.0,0.0,3.0
8,00-03-02-06,8,Wajir,North Eastern,1.0,2.0,3.0,1.0,3.0,3.0,0.0,3.0,0.0,2.0
9,00-03-71-00,29,Nandi,Rift Valley,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0


The result is a respondent-level table that combines demographics, county names, regional labels, financial access indicators, and financial health measures. This confirms that the split-table data structure supports integrated analysis when respondent identifiers and county codes are aligned.


### 6. Urban and Non-Urban Comparison

Major urban counties are compared with broader regional groups to assess whether formal and digital access is concentrated in urban markets. The result helps distinguish national reach from market depth.


In [9]:
# Urban and non-urban comparisons show whether inclusion depth is concentrated in major markets.
query = """
SELECT
    'Urban benchmark: selected major centre counties' AS comparison_group,
    'Nairobi, Mombasa, Kisumu, Nakuru, Uasin Gishu' AS region_or_county_group,
    COUNT(DISTINCT cr.county_code) AS county_count,
    COUNT(*) AS respondent_count,
    ROUND(AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS mobile_money_use_rate_percent,
    ROUND(AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS bank_use_rate_percent,
    ROUND(AVG(CASE WHEN fm.bank_use = 1 AND fm.mobile_money_use = 1 THEN 1.0 ELSE 0.0 END) * 100, 2) AS fully_included_rate_percent
FROM finaccess_master fm
INNER JOIN county_reference cr
    ON CAST(fm.county AS INTEGER) = cr.county_code
WHERE cr.county_code IN (47, 1, 42, 32, 27)

UNION ALL

SELECT
    'Rural/non-major-urban counties by region' AS comparison_group,
    cr.region AS region_or_county_group,
    COUNT(DISTINCT cr.county_code) AS county_count,
    COUNT(*) AS respondent_count,
    ROUND(AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS mobile_money_use_rate_percent,
    ROUND(AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100, 2) AS bank_use_rate_percent,
    ROUND(AVG(CASE WHEN fm.bank_use = 1 AND fm.mobile_money_use = 1 THEN 1.0 ELSE 0.0 END) * 100, 2) AS fully_included_rate_percent
FROM finaccess_master fm
INNER JOIN county_reference cr
    ON CAST(fm.county AS INTEGER) = cr.county_code
WHERE cr.county_code NOT IN (47, 1, 42, 32, 27)
GROUP BY cr.region
ORDER BY comparison_group, region_or_county_group;
"""

df_urban_rural_comparison = pd.read_sql(query, engine)
df_urban_rural_comparison

,comparison_group,region_or_county_group,county_count,respondent_count,mobile_money_use_rate_percent,bank_use_rate_percent,fully_included_rate_percent
0,Rural/non-major-urban counties by region,Central,5,2451,84.82,55.61,53.49
1,Rural/non-major-urban counties by region,Coast,5,1892,78.36,36.98,36.42
2,Rural/non-major-urban counties by region,Eastern,8,3598,81.24,46.36,44.72
3,Rural/non-major-urban counties by region,North Eastern,3,1114,80.97,20.38,20.29
4,Rural/non-major-urban counties by region,Nyanza,5,2448,76.76,41.42,40.24
5,Rural/non-major-urban counties by region,Rift Valley,12,4713,73.66,44.10,42.63
6,Rural/non-major-urban counties by region,Western,4,1956,71.97,44.55,41.77
7,Urban benchmark: selected major centre counties,"Nairobi, Mombasa, Kisumu, Nakuru, Uasin Gishu",5,2699,84.43,58.52,57.43


The selected urban benchmark has `84.43` percent mobile money use, `58.52` percent bank use, and a simplified fully included rate of `57.43` percent. Among the non-major-urban regional groups, Central is closest on the fully included measure at `53.49` percent. North Eastern has strong mobile money use at `80.97` percent but much lower bank use at `20.38` percent and fully included rate at `20.29` percent.

This result shows why geography matters for financial inclusion strategy. Mobile money can reach beyond the largest urban centres, but bank-linked inclusion remains uneven. A fintech might prioritise lightweight mobile-first products, agent liquidity, offline onboarding, or alternative credit assessment in regions where bank use is low. NGOs and development organisations might use the same evidence to design region-specific financial capability, savings, insurance, or resilience programmes.


### 7. County Mobile Money Benchmark

County mobile money rates are compared with the national average to identify overperforming and underperforming counties. This highlights where digital finance is already embedded and where adoption gaps remain.


In [10]:
# National benchmarking identifies counties leading or lagging in mobile money adoption.
query = """
WITH county_rates AS (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        COUNT(*) AS respondent_count,
        AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
),
national_rate AS (
    SELECT
        AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS national_mobile_money_use_rate_percent
    FROM finaccess_master
)
SELECT
    cr.county_code,
    ref.county_name,
    ref.region,
    cr.respondent_count,
    ROUND(cr.mobile_money_use_rate_percent, 2) AS county_mobile_money_use_rate_percent,
    ROUND(nr.national_mobile_money_use_rate_percent, 2) AS national_mobile_money_use_rate_percent,
    ROUND(cr.mobile_money_use_rate_percent - nr.national_mobile_money_use_rate_percent, 2) AS difference_from_national_percentage_points,
    CASE
        WHEN cr.mobile_money_use_rate_percent > nr.national_mobile_money_use_rate_percent THEN 'Above national average'
        WHEN cr.mobile_money_use_rate_percent < nr.national_mobile_money_use_rate_percent THEN 'Below national average'
        ELSE 'Equal to national average'
    END AS comparison_to_national
FROM county_rates cr
INNER JOIN national_rate nr
    ON 1 = 1
INNER JOIN county_reference ref
    ON cr.county_code = ref.county_code
ORDER BY difference_from_national_percentage_points DESC;
"""

df_county_vs_national_mobile_money = pd.read_sql(query, engine)
df_county_vs_national_mobile_money

,county_code,county_name,region,respondent_count,county_mobile_money_use_rate_percent,national_mobile_money_use_rate_percent,difference_from_national_percentage_points,comparison_to_national
0,47,Nairobi,Nairobi,622,92.93,78.69,14.23,Above national average
1,19,Nyeri,Central,457,89.93,78.69,11.24,Above national average
2,14,Embu,Eastern,478,87.03,78.69,8.34,Above national average
3,6,Taita Taveta,Coast,394,86.29,78.69,7.60,Above national average
4,20,Kirinyaga,Central,508,86.22,78.69,7.53,Above national average
5,22,Kiambu,Central,541,86.11,78.69,7.42,Above national average
6,31,Laikipia,Rift Valley,377,84.62,78.69,5.92,Above national average
7,28,Elgeyo-Marakwet,Rift Valley,426,83.80,78.69,5.11,Above national average
8,18,Nyandarua,Central,429,83.68,78.69,4.99,Above national average
9,27,Uasin Gishu,Rift Valley,551,83.48,78.69,4.79,Above national average


The national mobile money use rate is `78.69` percent in the validated output. Nairobi is `14.23` percentage points above the national average, followed by Nyeri at `11.24` points above and Embu at `8.34` points above. At the lower end, West Pokot is `33.36` percentage points below the national average, while Turkana and Baringo are also notably below the national benchmark.

This comparison helps turn a national statistic into an actionable geographic diagnostic. Counties above the national average may be strong candidates for more advanced digital financial products, while counties below the national average may require investments in agent networks, affordability, mobile access, trust, consumer education, or complementary livelihood support. For NGOs and development organisations, below-average counties can guide targeting. For fintechs, the same benchmark can inform market entry, customer acquisition cost assumptions, and product-channel strategy.


## Section 5: County Benchmarks and Scorecards

This section compares counties against national and peer benchmarks. The results identify leading counties, lagging counties, and the scale of variation behind national averages.


### 1. Counties Above the National Mobile Money Average

Counties above the national mobile money benchmark show where digital finance has already reached high levels of adoption. These markets may support deeper products such as savings, credit, insurance, and merchant services.


In [11]:
# Above-average counties indicate markets where digital finance is already deeply adopted.
query = """
SELECT
    cr.county_code,
    cr.county_name,
    cr.region,
    county_rates.respondent_count,
    ROUND(county_rates.mobile_money_use_rate_percent, 2) AS county_mobile_money_use_rate_percent
FROM (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        COUNT(*) AS respondent_count,
        AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
) county_rates
INNER JOIN county_reference cr
    ON county_rates.county_code = cr.county_code
WHERE county_rates.mobile_money_use_rate_percent > (
    SELECT AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100
    FROM finaccess_master
)
ORDER BY county_rates.mobile_money_use_rate_percent DESC;
"""

df_counties_above_mobile_average = pd.read_sql(query, engine)
df_counties_above_mobile_average

,county_code,county_name,region,respondent_count,county_mobile_money_use_rate_percent
0,47,Nairobi,Nairobi,622,92.93
1,19,Nyeri,Central,457,89.93
2,14,Embu,Eastern,478,87.03
3,6,Taita Taveta,Coast,394,86.29
4,20,Kirinyaga,Central,508,86.22
5,22,Kiambu,Central,541,86.11
6,31,Laikipia,Rift Valley,377,84.62
7,28,Elgeyo-Marakwet,Rift Valley,426,83.80
8,18,Nyandarua,Central,429,83.68
9,27,Uasin Gishu,Rift Valley,551,83.48


The result identifies `27` counties with mobile money use above the national benchmark of about `78.69` percent. Nairobi leads at `92.93` percent, followed by Nyeri at `89.93` percent and Embu at `87.03` percent. Several counties outside Nairobi also exceed the national average, showing that strong mobile money adoption is not limited to the capital.

For fintechs, these counties may be suitable for digital-first products because many respondents already report mobile money use. For NGOs and development organisations, the result can help distinguish places where digital rails are already widely used from places where additional work may be needed around access, agent networks, affordability, or user confidence.


### 2. County Performance Relative to the Leader

Expressing each county as a share of the top county shows the size of the adoption gap. This makes performance differences easier to interpret than rates alone.


In [12]:
# Leader-relative rates show the size of county adoption gaps.
query = """
SELECT
    cr.county_code,
    cr.county_name,
    cr.region,
    ROUND(county_rates.mobile_money_use_rate_percent, 2) AS county_mobile_money_use_rate_percent,
    ROUND(
        county_rates.mobile_money_use_rate_percent * 100.0 /
        (
            SELECT MAX(highest_rates.mobile_money_use_rate_percent)
            FROM (
                SELECT
                    AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent
                FROM finaccess_master
                GROUP BY CAST(county AS INTEGER)
            ) highest_rates
        ),
        2
    ) AS percent_of_highest_county_rate
FROM (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
) county_rates
INNER JOIN county_reference cr
    ON county_rates.county_code = cr.county_code
ORDER BY percent_of_highest_county_rate DESC;
"""

df_mobile_rate_percent_of_highest = pd.read_sql(query, engine)
df_mobile_rate_percent_of_highest

,county_code,county_name,region,county_mobile_money_use_rate_percent,percent_of_highest_county_rate
0,47,Nairobi,Nairobi,92.93,100.00
1,19,Nyeri,Central,89.93,96.78
2,14,Embu,Eastern,87.03,93.65
3,6,Taita Taveta,Coast,86.29,92.86
4,20,Kirinyaga,Central,86.22,92.78
5,22,Kiambu,Central,86.11,92.67
6,31,Laikipia,Rift Valley,84.62,91.06
7,28,Elgeyo-Marakwet,Rift Valley,83.80,90.18
8,18,Nyandarua,Central,83.68,90.05
9,27,Uasin Gishu,Rift Valley,83.48,89.84


The result sets Nairobi as the highest-performing county at `100.00` percent of the best observed mobile money rate. Nyeri reaches `96.78` percent of Nairobi's rate, while Embu reaches `93.65` percent. At the bottom, West Pokot is `48.78` percent of the highest county rate.

This benchmark view is useful because it translates a technical rate into a relative performance measure. A fintech could use it to identify counties close to the digital-finance frontier. A development organisation could use the same measure to identify counties that may need foundational digital finance support before more advanced products are introduced.


### 3. Respondent Literacy Relative to County Average

Comparing respondent financial literacy with the county average highlights within-county inequality. This is useful for designing financial capability interventions that target below-average groups locally.


In [13]:
# County literacy benchmarks identify respondents who may need local capability support.
query = """
SELECT
    fm.interview__key,
    CAST(fm.county AS INTEGER) AS county_code,
    cr.county_name,
    fm."Financial_literacy_index_fnl" AS respondent_financial_literacy_score,
    ROUND((
        SELECT AVG(fm2."Financial_literacy_index_fnl")::numeric
        FROM finaccess_master fm2
        WHERE CAST(fm2.county AS INTEGER) = CAST(fm.county AS INTEGER)
    ), 2) AS county_avg_financial_literacy_score,
    CASE
        WHEN fm."Financial_literacy_index_fnl" > (
            SELECT AVG(fm2."Financial_literacy_index_fnl")
            FROM finaccess_master fm2
            WHERE CAST(fm2.county AS INTEGER) = CAST(fm.county AS INTEGER)
        ) THEN 'Above county average'
        WHEN fm."Financial_literacy_index_fnl" < (
            SELECT AVG(fm2."Financial_literacy_index_fnl")
            FROM finaccess_master fm2
            WHERE CAST(fm2.county AS INTEGER) = CAST(fm.county AS INTEGER)
        ) THEN 'Below county average'
        ELSE 'Equal to county average'
    END AS literacy_position_within_county
FROM finaccess_master fm
INNER JOIN county_reference cr
    ON CAST(fm.county AS INTEGER) = cr.county_code
ORDER BY fm.interview__key
LIMIT 25;
"""

df_literacy_vs_county_average = pd.read_sql(query, engine)
df_literacy_vs_county_average

,interview__key,county_code,county_name,respondent_financial_literacy_score,county_avg_financial_literacy_score,literacy_position_within_county
0,00-00-18-74,27,Uasin Gishu,1.0,1.56,Below county average
1,00-00-59-38,13,Tharaka-Nithi,1.0,1.82,Below county average
2,00-01-02-96,36,Bomet,1.0,1.85,Below county average
3,00-01-21-44,11,Isiolo,2.0,2.11,Below county average
4,00-01-36-47,46,Nyamira,1.0,1.90,Below county average
5,00-01-41-64,34,Kajiado,2.0,2.33,Below county average
6,00-01-81-79,36,Bomet,1.0,1.85,Below county average
7,00-02-87-76,46,Nyamira,2.0,1.90,Above county average
8,00-03-02-06,8,Wajir,2.0,2.37,Below county average
9,00-03-71-00,29,Nandi,3.0,1.76,Above county average


The sample result shows respondent-level financial literacy scores beside county-level averages. Respondents below their county average represent a useful audience for financial capability support, while higher-scoring respondents may be better positioned to use more complex products.


### 4. County Mobile Money Ranking

County mobile money rankings identify where digital finance is most and least adopted. These rankings help prioritise market deepening in high-use counties and adoption support in low-use counties.


In [14]:
# County mobile money rankings identify priority markets for digital finance deepening.
query = """
WITH county_mobile_money AS (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        COUNT(*) AS respondent_count,
        AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
)
SELECT
    cmm.county_code,
    cr.county_name,
    cr.region,
    cmm.respondent_count,
    ROUND(cmm.mobile_money_use_rate_percent, 2) AS mobile_money_use_rate_percent
FROM county_mobile_money cmm
INNER JOIN county_reference cr
    ON cmm.county_code = cr.county_code
ORDER BY mobile_money_use_rate_percent DESC;
"""

df_county_mobile_money_cte = pd.read_sql(query, engine)
df_county_mobile_money_cte

,county_code,county_name,region,respondent_count,mobile_money_use_rate_percent
0,47,Nairobi,Nairobi,622,92.93
1,19,Nyeri,Central,457,89.93
2,14,Embu,Eastern,478,87.03
3,6,Taita Taveta,Coast,394,86.29
4,20,Kirinyaga,Central,508,86.22
5,22,Kiambu,Central,541,86.11
6,31,Laikipia,Rift Valley,377,84.62
7,28,Elgeyo-Marakwet,Rift Valley,426,83.80
8,18,Nyandarua,Central,429,83.68
9,27,Uasin Gishu,Rift Valley,551,83.48


The result ranks all counties by mobile money use rate. Nairobi leads at `92.93%`, followed by Nyeri, Embu, Taita Taveta, Kirinyaga, and Kiambu, while West Pokot appears at the bottom at `45.33%`.

This spread shows that digital finance adoption is broad nationally but still uneven across counties.


### 5. County Rates Against National Benchmarks

County rates are compared with national mobile money, bank, and combined access benchmarks. This shows whether counties are broadly included or dependent on only one access channel.


In [15]:
# National benchmarks separate broad inclusion from dependence on a single access channel.
query = """
WITH county_inclusion_rates AS (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        COUNT(*) AS respondent_count,
        AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent,
        AVG(CASE WHEN bank_use = 1 THEN 1.0 WHEN bank_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS bank_use_rate_percent,
        AVG(CASE WHEN "Savings_usage" = 1 THEN 1.0 WHEN "Savings_usage" IS NULL THEN NULL ELSE 0.0 END) * 100 AS savings_usage_rate_percent,
        AVG(CASE WHEN bank_use = 1 AND mobile_money_use = 1 THEN 1.0 ELSE 0.0 END) * 100 AS fully_included_rate_percent
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
),
national_averages AS (
    SELECT
        AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS national_mobile_money_use_rate_percent,
        AVG(CASE WHEN bank_use = 1 THEN 1.0 WHEN bank_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS national_bank_use_rate_percent,
        AVG(CASE WHEN "Savings_usage" = 1 THEN 1.0 WHEN "Savings_usage" IS NULL THEN NULL ELSE 0.0 END) * 100 AS national_savings_usage_rate_percent,
        AVG(CASE WHEN bank_use = 1 AND mobile_money_use = 1 THEN 1.0 ELSE 0.0 END) * 100 AS national_fully_included_rate_percent
    FROM finaccess_master
)
SELECT
    cr.county_code,
    cr.county_name,
    cr.region,
    cir.respondent_count,
    ROUND(cir.mobile_money_use_rate_percent, 2) AS county_mobile_money_use_rate_percent,
    ROUND(na.national_mobile_money_use_rate_percent, 2) AS national_mobile_money_use_rate_percent,
    CASE WHEN cir.mobile_money_use_rate_percent >= na.national_mobile_money_use_rate_percent THEN 'Above or equal to national average' ELSE 'Below national average' END AS mobile_money_benchmark_flag,
    ROUND(cir.bank_use_rate_percent, 2) AS county_bank_use_rate_percent,
    ROUND(na.national_bank_use_rate_percent, 2) AS national_bank_use_rate_percent,
    CASE WHEN cir.bank_use_rate_percent >= na.national_bank_use_rate_percent THEN 'Above or equal to national average' ELSE 'Below national average' END AS bank_use_benchmark_flag,
    ROUND(cir.fully_included_rate_percent, 2) AS county_fully_included_rate_percent,
    ROUND(na.national_fully_included_rate_percent, 2) AS national_fully_included_rate_percent,
    CASE WHEN cir.fully_included_rate_percent >= na.national_fully_included_rate_percent THEN 'Above or equal to national average' ELSE 'Below national average' END AS fully_included_benchmark_flag
FROM county_inclusion_rates cir
INNER JOIN county_reference cr
    ON cir.county_code = cr.county_code
CROSS JOIN national_averages na
ORDER BY county_fully_included_rate_percent DESC;
"""

df_county_vs_national_cte = pd.read_sql(query, engine)
df_county_vs_national_cte

,county_code,county_name,region,respondent_count,county_mobile_money_use_rate_percent,national_mobile_money_use_rate_percent,mobile_money_benchmark_flag,county_bank_use_rate_percent,national_bank_use_rate_percent,bank_use_benchmark_flag,county_fully_included_rate_percent,national_fully_included_rate_percent,fully_included_benchmark_flag
0,47,Nairobi,Nairobi,622,92.93,78.69,Above or equal to national average,72.99,45.52,Above or equal to national average,72.67,44.06,Above or equal to national average
1,22,Kiambu,Central,541,86.11,78.69,Above or equal to national average,66.98,45.52,Above or equal to national average,64.88,44.06,Above or equal to national average
2,27,Uasin Gishu,Rift Valley,551,83.48,78.69,Above or equal to national average,61.16,45.52,Above or equal to national average,59.89,44.06,Above or equal to national average
3,19,Nyeri,Central,457,89.93,78.69,Above or equal to national average,59.30,45.52,Above or equal to national average,58.21,44.06,Above or equal to national average
4,29,Nandi,Rift Valley,475,81.68,78.69,Above or equal to national average,59.58,45.52,Above or equal to national average,56.84,44.06,Above or equal to national average
5,34,Kajiado,Rift Valley,412,81.07,78.69,Above or equal to national average,56.07,45.52,Above or equal to national average,55.83,44.06,Above or equal to national average
6,6,Taita Taveta,Coast,394,86.29,78.69,Above or equal to national average,54.57,45.52,Above or equal to national average,54.06,44.06,Above or equal to national average
7,28,Elgeyo-Marakwet,Rift Valley,426,83.80,78.69,Above or equal to national average,53.99,45.52,Above or equal to national average,53.76,44.06,Above or equal to national average
8,26,Trans Nzoia,Rift Valley,162,74.69,78.69,Below national average,53.70,45.52,Above or equal to national average,53.70,44.06,Above or equal to national average
9,14,Embu,Eastern,478,87.03,78.69,Above or equal to national average,54.18,45.52,Above or equal to national average,53.35,44.06,Above or equal to national average


The benchmark result shows national benchmarks of about `78.69` percent for mobile money use, `45.52` percent for bank use, and `44.06` percent for the simplified fully included measure. Nairobi, Kiambu, Uasin Gishu, Nyeri, and Nandi perform above the national benchmark on the combined bank-and-mobile measure. Some counties, such as Mandera and Wajir, are above the national mobile money benchmark but below the bank-use and fully included benchmarks.

This is a more nuanced interpretation than mobile money alone. It shows that digital access and bank-linked inclusion can diverge. Fintechs can use this to distinguish mobile-ready markets from markets ready for bank-linked products. NGOs and development organisations can use the same logic to identify places where mobile channels exist but broader formal inclusion remains weak.


### 6. County Financial Inclusion Scorecard

The county scorecard brings together demographics, product usage, financial health, vulnerability, and literacy. This gives stakeholders a more complete view than access rates alone.


In [16]:
# County scorecards combine demographic, access, and wellbeing signals for decisions.
query = """
WITH county_demographics AS (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        COUNT(*) AS respondent_count,
        AVG("Age") AS avg_age_code,
        AVG(CASE WHEN "Sex" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS sex_code_1_share_percent,
        AVG(CASE WHEN "Sex" = 2 THEN 1.0 ELSE 0.0 END) * 100 AS sex_code_2_share_percent,
        AVG(CASE WHEN "Education" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS education_code_1_share_percent,
        AVG(CASE WHEN "Education" = 2 THEN 1.0 ELSE 0.0 END) * 100 AS education_code_2_share_percent,
        AVG(CASE WHEN "Education" = 3 THEN 1.0 ELSE 0.0 END) * 100 AS education_code_3_share_percent,
        AVG(CASE WHEN "Education" = 4 THEN 1.0 ELSE 0.0 END) * 100 AS education_code_4_share_percent,
        AVG(CASE WHEN "Education" = 5 THEN 1.0 ELSE 0.0 END) * 100 AS education_code_5_share_percent
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
),
county_access_rates AS (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent,
        AVG(CASE WHEN bank_use = 1 THEN 1.0 WHEN bank_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS bank_use_rate_percent,
        AVG(CASE WHEN "Savings_usage" = 1 THEN 1.0 WHEN "Savings_usage" IS NULL THEN NULL ELSE 0.0 END) * 100 AS savings_usage_rate_percent,
        AVG(CASE WHEN "Loan_usage" = 1 THEN 1.0 WHEN "Loan_usage" IS NULL THEN NULL ELSE 0.0 END) * 100 AS loan_usage_rate_percent,
        AVG(CASE WHEN bank_use = 1 AND mobile_money_use = 1 THEN 1.0 ELSE 0.0 END) * 100 AS fully_included_rate_percent
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
),
county_health_scores AS (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        AVG(finhealth_fnl) AS avg_finhealth_fnl,
        AVG(vul_index_fnl) AS avg_vul_index_fnl,
        AVG("Financial_literacy_index_fnl") AS avg_financial_literacy_index_fnl
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
)
SELECT
    cr.county_code,
    cr.county_name,
    cr.region,
    cd.respondent_count,
    ROUND(cd.avg_age_code::numeric, 2) AS avg_age_code,
    ROUND(cd.sex_code_1_share_percent::numeric, 2) AS sex_code_1_share_percent,
    ROUND(cd.sex_code_2_share_percent::numeric, 2) AS sex_code_2_share_percent,
    ROUND(cd.education_code_1_share_percent::numeric, 2) AS education_code_1_share_percent,
    ROUND(cd.education_code_2_share_percent::numeric, 2) AS education_code_2_share_percent,
    ROUND(cd.education_code_3_share_percent::numeric, 2) AS education_code_3_share_percent,
    ROUND(cd.education_code_4_share_percent::numeric, 2) AS education_code_4_share_percent,
    ROUND(cd.education_code_5_share_percent::numeric, 2) AS education_code_5_share_percent,
    ROUND(car.mobile_money_use_rate_percent::numeric, 2) AS mobile_money_use_rate_percent,
    ROUND(car.bank_use_rate_percent::numeric, 2) AS bank_use_rate_percent,
    ROUND(car.savings_usage_rate_percent::numeric, 2) AS savings_usage_rate_percent,
    ROUND(car.loan_usage_rate_percent::numeric, 2) AS loan_usage_rate_percent,
    ROUND(car.fully_included_rate_percent::numeric, 2) AS fully_included_rate_percent,
    ROUND(chs.avg_finhealth_fnl::numeric, 2) AS avg_finhealth_fnl,
    ROUND(chs.avg_vul_index_fnl::numeric, 2) AS avg_vul_index_fnl,
    ROUND(chs.avg_financial_literacy_index_fnl::numeric, 2) AS avg_financial_literacy_index_fnl
FROM county_demographics cd
INNER JOIN county_access_rates car
    ON cd.county_code = car.county_code
INNER JOIN county_health_scores chs
    ON cd.county_code = chs.county_code
INNER JOIN county_reference cr
    ON cd.county_code = cr.county_code
ORDER BY fully_included_rate_percent DESC;
"""

df_county_scorecard = pd.read_sql(query, engine)
df_county_scorecard

,county_code,county_name,region,respondent_count,avg_age_code,sex_code_1_share_percent,sex_code_2_share_percent,education_code_1_share_percent,education_code_2_share_percent,education_code_3_share_percent,education_code_4_share_percent,education_code_5_share_percent,mobile_money_use_rate_percent,bank_use_rate_percent,savings_usage_rate_percent,loan_usage_rate_percent,fully_included_rate_percent,avg_finhealth_fnl,avg_vul_index_fnl,avg_financial_literacy_index_fnl
0,47,Nairobi,Nairobi,622,3.26,43.89,56.11,1.13,20.26,47.91,30.71,0.00,92.93,72.99,87.14,63.83,72.67,0.36,2.64,1.95
1,22,Kiambu,Central,541,3.68,51.39,48.61,2.40,35.49,41.59,20.52,0.00,86.11,66.98,78.19,74.86,64.88,0.23,2.61,1.44
2,27,Uasin Gishu,Rift Valley,551,3.36,45.55,54.45,2.36,28.49,45.92,23.23,0.00,83.48,61.16,73.14,62.61,59.89,0.15,2.63,1.56
3,19,Nyeri,Central,457,4.02,38.95,61.05,3.28,33.26,47.05,16.41,0.00,89.93,59.30,67.61,64.11,58.21,0.17,2.56,1.75
4,29,Nandi,Rift Valley,475,3.66,42.53,57.47,3.79,46.74,34.32,15.16,0.00,81.68,59.58,74.32,72.63,56.84,0.13,2.53,1.76
5,34,Kajiado,Rift Valley,412,3.45,38.11,61.89,18.20,22.57,41.02,18.20,0.00,81.07,56.07,85.92,61.65,55.83,0.28,2.50,2.33
6,6,Taita Taveta,Coast,394,3.77,44.42,55.58,6.85,37.31,42.39,13.45,0.00,86.29,54.57,55.33,63.96,54.06,0.22,2.38,1.78
7,28,Elgeyo-Marakwet,Rift Valley,426,3.68,42.49,57.51,4.23,40.61,37.09,18.08,0.00,83.80,53.99,78.17,72.54,53.76,0.16,2.60,1.66
8,26,Trans Nzoia,Rift Valley,162,3.40,42.59,57.41,3.09,34.57,38.89,23.46,0.00,74.69,53.70,47.53,58.02,53.70,0.09,2.85,1.41
9,14,Embu,Eastern,478,4.09,45.40,54.60,3.77,42.47,33.68,20.08,0.00,87.03,54.18,75.94,67.57,53.35,0.18,2.65,1.98


The scorecard combines several layers of county information in one result. It shows, for example, that high-performing counties on the simplified fully included measure can be reviewed alongside their age profile, sex-code shares, education-code mix, savings and loan usage, average financial health, vulnerability, and financial literacy scores.

This is valuable because financial inclusion is multidimensional. A county may have high mobile money use but lower bank use, lower financial health, or a different education profile. For fintechs, a scorecard supports market prioritisation and product localisation.


### 7. Highest and Lowest Overall Access Counties

Ranking counties by overall access identifies where inclusion is strongest and where exclusion risk is most concentrated. This supports prioritisation for public and development-sector interventions.


In [17]:
# Highest and lowest access counties guide opportunity sizing and intervention targeting.
query = """
WITH county_access AS (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        COUNT(*) AS respondent_count,
        AVG(CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS overall_access_rate_percent
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
),
ranked_counties AS (
    SELECT
        ca.*,
        ROW_NUMBER() OVER (ORDER BY ca.overall_access_rate_percent DESC) AS top_rank,
        ROW_NUMBER() OVER (ORDER BY ca.overall_access_rate_percent ASC) AS bottom_rank
    FROM county_access ca
),
ranked_output AS (
    SELECT
        1 AS group_sort,
        'Top 10 counties' AS performance_group,
        top_rank AS rank_position,
        county_code,
        respondent_count,
        overall_access_rate_percent
    FROM ranked_counties
    WHERE top_rank <= 10
    UNION ALL
    SELECT
        2 AS group_sort,
        'Bottom 10 counties' AS performance_group,
        bottom_rank AS rank_position,
        county_code,
        respondent_count,
        overall_access_rate_percent
    FROM ranked_counties
    WHERE bottom_rank <= 10
)
SELECT
    ro.performance_group,
    ro.rank_position,
    cr.county_name,
    cr.region,
    ro.respondent_count,
    ROUND(ro.overall_access_rate_percent, 2) AS overall_access_rate_percent
FROM ranked_output ro
INNER JOIN county_reference cr
    ON ro.county_code = cr.county_code
ORDER BY ro.group_sort, ro.rank_position;
"""

df_top_bottom_overall_access = pd.read_sql(query, engine)
df_top_bottom_overall_access

,performance_group,rank_position,county_name,region,respondent_count,overall_access_rate_percent
0,Top 10 counties,1,Nairobi,Nairobi,622,93.73
1,Top 10 counties,2,Nyeri,Central,457,92.12
2,Top 10 counties,3,Kirinyaga,Central,508,91.54
3,Top 10 counties,4,Embu,Eastern,478,90.17
4,Top 10 counties,5,Kiambu,Central,541,89.65
5,Top 10 counties,6,Taita Taveta,Coast,394,86.80
6,Top 10 counties,7,Nandi,Rift Valley,475,86.74
7,Top 10 counties,8,Nyandarua,Central,429,86.48
8,Top 10 counties,9,Laikipia,Rift Valley,377,86.47
9,Top 10 counties,10,Elgeyo-Marakwet,Rift Valley,426,85.92


The ranked output shows Nairobi at the top with an overall access rate of `93.73` percent under this working definition, followed by Nyeri, Kirinyaga, Embu, and Kiambu. The bottom 10 include West Pokot, Turkana, Tana River, Narok, Migori, Kakamega, Siaya, Busia, Baringo, and Kilifi.

For policy and implementation, this is a clear prioritisation tool. Top-performing counties can be studied to understand enabling conditions, while bottom-performing counties can be examined for barriers such as infrastructure, income volatility, distance, documentation, product fit, or trust.


### 8. Income Quintile Access Gradient

Income quintile results show whether financial access rises with household welfare. This is central to assessing whether inclusion is equitable or concentrated among better-off groups.


In [18]:
# Cumulative welfare-group rates show how inclusion changes as household welfare rises.
query = """
WITH RECURSIVE quintile_sequence(quintile) AS (
    SELECT 1
    UNION ALL
    SELECT quintile + 1
    FROM quintile_sequence
    WHERE quintile < 5
),
quintile_summary AS (
    SELECT
        qs.quintile,
        COUNT(fm.*) AS quintile_respondents,
        AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS quintile_overall_access_rate_percent
    FROM quintile_sequence qs
    LEFT JOIN finaccess_master fm
        ON CAST(fm."Quintiles" AS INTEGER) = qs.quintile
    GROUP BY qs.quintile
),
cumulative_summary AS (
    SELECT
        qs.quintile,
        COUNT(fm.*) AS cumulative_respondents,
        AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS cumulative_overall_access_rate_percent
    FROM quintile_sequence qs
    LEFT JOIN finaccess_master fm
        ON CAST(fm."Quintiles" AS INTEGER) <= qs.quintile
    GROUP BY qs.quintile
)
SELECT
    qs.quintile,
    qsum.quintile_respondents,
    ROUND(qsum.quintile_overall_access_rate_percent::numeric, 2) AS quintile_overall_access_rate_percent,
    csum.cumulative_respondents,
    ROUND(csum.cumulative_overall_access_rate_percent::numeric, 2) AS cumulative_overall_access_rate_percent
FROM quintile_sequence qs
INNER JOIN quintile_summary qsum
    ON qs.quintile = qsum.quintile
INNER JOIN cumulative_summary csum
    ON qs.quintile = csum.quintile
ORDER BY qs.quintile;
"""

df_recursive_quintile_access = pd.read_sql(query, engine)
df_recursive_quintile_access

,quintile,quintile_respondents,quintile_overall_access_rate_percent,cumulative_respondents,cumulative_overall_access_rate_percent
0,1,4973,68.57,4973,68.57
1,2,4478,77.58,9451,72.84
2,3,4293,84.91,13744,76.61
3,4,4232,89.51,17976,79.65
4,5,2859,92.83,20835,81.45


The income result shows a clear welfare gradient. Quintile `1` has an overall access rate of `68.57` percent under the working definition, while quintile `5` reaches `92.83` percent. The cumulative rate rises from `68.57` percent at quintile `1` to `81.45` percent after including all five quintiles with non-null quintile data.

For financial inclusion policy, this reinforces the importance of income or welfare position. Access improves as higher quintiles are added, which suggests that inclusion is connected to broader socioeconomic conditions. For fintechs, lower-quintile groups may require lower-cost products, simpler onboarding, consumer protection, and stronger trust mechanisms.


## Section 6: Rankings, Peer Comparisons, and Inequality

This section examines county rankings, peer comparisons, quartiles, cumulative coverage, and respondent-level gaps. The findings show how inequality appears within and across counties.


### 1. Respondent Ordering Within Counties

County-specific ordering supports inspection of respondent records within each geography. This is useful when reviewing local samples and checking demographic patterns by county.


In [19]:
# County-specific respondent ordering supports structured local sample review.
query = """
SELECT
    interview__key,
    county,
    county_name,
    "Sex",
    "Age",
    ROW_NUMBER() OVER (
        PARTITION BY county
        ORDER BY "Age", interview__key
    ) AS respondent_row_number_within_county
FROM finaccess_clean
ORDER BY county, respondent_row_number_within_county
LIMIT 30;
"""

df_county_row_numbers = pd.read_sql(query, engine)
df_county_row_numbers

,interview__key,county,county_name,Sex,Age,respondent_row_number_within_county
0,01-64-65-55,1,Mombasa,1.0,1.0,1
1,02-52-45-78,1,Mombasa,1.0,1.0,2
2,07-77-57-61,1,Mombasa,2.0,1.0,3
3,26-64-37-72,1,Mombasa,2.0,1.0,4
4,28-70-65-85,1,Mombasa,2.0,1.0,5
5,32-05-85-11,1,Mombasa,2.0,1.0,6
6,35-26-42-17,1,Mombasa,1.0,1.0,7
7,43-36-04-54,1,Mombasa,1.0,1.0,8
8,56-44-64-13,1,Mombasa,2.0,1.0,9
9,64-83-33-51,1,Mombasa,1.0,1.0,10


The sample output shows respondents ordered within each county, beginning with Mombasa. County-specific ordering supports structured record review and makes it easier to inspect local respondent patterns without mixing counties.


### 2. County Mobile Money Rank Positions

Ranked mobile money rates show how counties compare after rounding. Shared ranks reveal counties with similar adoption levels, which can be grouped for comparable interventions.


In [20]:
# Tie-aware performance bands group counties with similar mobile money adoption levels.
query = """
WITH county_rates AS (
    SELECT
        cr.county_code,
        cr.county_name,
        cr.region,
        COUNT(*) AS respondent_count,
        AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    GROUP BY cr.county_code, cr.county_name, cr.region
),
ranked_counties AS (
    SELECT
        county_code,
        county_name,
        region,
        respondent_count,
        mobile_money_use_rate_percent,
        ROUND(mobile_money_use_rate_percent::numeric, 0) AS rounded_rate_for_tie_demo,
        RANK() OVER (ORDER BY ROUND(mobile_money_use_rate_percent::numeric, 0) DESC) AS rank_with_gaps,
        DENSE_RANK() OVER (ORDER BY ROUND(mobile_money_use_rate_percent::numeric, 0) DESC) AS dense_rank_without_gaps
    FROM county_rates
)
SELECT
    county_code,
    county_name,
    region,
    respondent_count,
    ROUND(mobile_money_use_rate_percent::numeric, 2) AS mobile_money_use_rate_percent,
    rounded_rate_for_tie_demo,
    rank_with_gaps,
    dense_rank_without_gaps
FROM ranked_counties
ORDER BY rounded_rate_for_tie_demo DESC, mobile_money_use_rate_percent DESC;
"""

df_rank_dense_rank_mobile = pd.read_sql(query, engine)
df_rank_dense_rank_mobile

,county_code,county_name,region,respondent_count,mobile_money_use_rate_percent,rounded_rate_for_tie_demo,rank_with_gaps,dense_rank_without_gaps
0,47,Nairobi,Nairobi,622,92.93,93.0,1,1
1,19,Nyeri,Central,457,89.93,90.0,2,2
2,14,Embu,Eastern,478,87.03,87.0,3,3
3,6,Taita Taveta,Coast,394,86.29,86.0,4,4
4,20,Kirinyaga,Central,508,86.22,86.0,4,4
5,22,Kiambu,Central,541,86.11,86.0,4,4
6,31,Laikipia,Rift Valley,377,84.62,85.0,7,5
7,28,Elgeyo-Marakwet,Rift Valley,426,83.80,84.0,8,6
8,18,Nyandarua,Central,429,83.68,84.0,8,6
9,27,Uasin Gishu,Rift Valley,551,83.48,83.0,10,7


The ranking shows Nairobi first with a rounded rate of `93`, followed by Nyeri at `90` and Embu at `87`. Taita Taveta, Kirinyaga, and Kiambu all round to `86`, placing them in the same performance band.

For stakeholders, the ranking highlights both clear leaders and peer groups with similar adoption levels. Peer grouping is useful for designing comparable county interventions rather than treating every county position as a materially different market.


### 3. County Access Tiers

County access tiers group counties from lower to higher overall access. The tiers provide a clear way to distinguish mature markets from counties needing deeper inclusion support.


In [21]:
# Access tiers turn county performance into practical priority bands.
query = """
WITH county_access AS (
    SELECT
        cr.county_code,
        cr.county_name,
        cr.region,
        COUNT(*) AS respondent_count,
        AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS overall_access_rate_percent
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    GROUP BY cr.county_code, cr.county_name, cr.region
),
quartiled AS (
    SELECT
        *,
        NTILE(4) OVER (ORDER BY overall_access_rate_percent ASC) AS access_quartile
    FROM county_access
)
SELECT
    CASE access_quartile
        WHEN 1 THEN 'Bronze'
        WHEN 2 THEN 'Silver'
        WHEN 3 THEN 'Gold'
        WHEN 4 THEN 'Platinum'
    END AS access_tier,
    access_quartile,
    county_code,
    county_name,
    region,
    respondent_count,
    ROUND(overall_access_rate_percent::numeric, 2) AS overall_access_rate_percent
FROM quartiled
ORDER BY access_quartile DESC, overall_access_rate_percent DESC;
"""

df_access_quartiles = pd.read_sql(query, engine)
df_access_quartiles

,access_tier,access_quartile,county_code,county_name,region,respondent_count,overall_access_rate_percent
0,Platinum,4,47,Nairobi,Nairobi,622,93.73
1,Platinum,4,19,Nyeri,Central,457,92.12
2,Platinum,4,20,Kirinyaga,Central,508,91.54
3,Platinum,4,14,Embu,Eastern,478,90.17
4,Platinum,4,22,Kiambu,Central,541,89.65
5,Platinum,4,6,Taita Taveta,Coast,394,86.80
6,Platinum,4,29,Nandi,Rift Valley,475,86.74
7,Platinum,4,18,Nyandarua,Central,429,86.48
8,Platinum,4,31,Laikipia,Rift Valley,377,86.47
9,Platinum,4,28,Elgeyo-Marakwet,Rift Valley,426,85.92


The county tiering places counties such as Nairobi, Nyeri, Kirinyaga, Embu, Kiambu, Taita Taveta, Nandi, Nyandarua, Laikipia, Elgeyo-Marakwet, and Nyamira in the `Platinum` tier. The `Bronze` tier includes counties such as West Pokot, Turkana, Tana River, Narok, Migori, Kakamega, Siaya, Busia, Baringo, Kilifi, Trans Nzoia, and Vihiga.

This tiering reveals geographic inequality in overall access. High-tier counties may be ready for more advanced financial services, while low-tier counties may need foundational interventions around access channels, affordability, literacy, identification, agent networks, or livelihoods. For analysis presentation, quartile labels make the result easier for non-technical audiences to understand.


### 4. Income Distribution Check

Income grouping confirms how respondents are distributed across welfare categories. This supports later comparisons of access, health, and vulnerability across income levels.


In [22]:
# Equal-sized income groups support distribution checks against official welfare coding.
query = """
WITH income_tiles AS (
    SELECT
        interview__key,
        "Quintiles" AS original_quintile,
        NTILE(5) OVER (ORDER BY "Quintiles", interview__key) AS ntile_income_group
    FROM finaccess_master
    WHERE "Quintiles" IS NOT NULL
)
SELECT
    ntile_income_group,
    COUNT(*) AS respondent_count,
    MIN(original_quintile) AS min_original_quintile_in_tile,
    MAX(original_quintile) AS max_original_quintile_in_tile,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM income_tiles), 2) AS sample_share_percent
FROM income_tiles
GROUP BY ntile_income_group
ORDER BY ntile_income_group;
"""

df_income_ntile_check = pd.read_sql(query, engine)
df_income_ntile_check

,ntile_income_group,respondent_count,min_original_quintile_in_tile,max_original_quintile_in_tile,sample_share_percent
0,1,4167,1.0,1.0,20.0
1,2,4167,1.0,2.0,20.0
2,3,4167,2.0,3.0,20.0
3,4,4167,3.0,4.0,20.0
4,5,4167,4.0,5.0,20.0


The income grouping produces five equally sized groups of `4,167` respondents each among records with non-null `"Quintiles"`. Each group represents `20.00%` of the non-null quintile sample.

For welfare analysis, the official `"Quintiles"` field remains the preferred basis for interpretation because it reflects the survey's income or welfare coding.


### 5. Cumulative County Coverage

Cumulative county counts confirm that county-level respondent totals reconcile to the national sample. This protects the integrity of national summaries built from county results.


In [23]:
# Cumulative totals confirm county counts reconcile to the national sample.
query = """
WITH county_counts AS (
    SELECT
        CAST(fm.county AS INTEGER) AS county_code,
        cr.county_name,
        cr.region,
        COUNT(*) AS respondent_count
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    GROUP BY CAST(fm.county AS INTEGER), cr.county_name, cr.region
)
SELECT
    county_code,
    county_name,
    region,
    respondent_count,
    SUM(respondent_count) OVER (
        ORDER BY county_code
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS running_total_respondents,
    ROUND(
        SUM(respondent_count) OVER (
            ORDER BY county_code
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) * 100.0 / SUM(respondent_count) OVER (),
        2
    ) AS cumulative_sample_percent
FROM county_counts
ORDER BY county_code;
"""

df_running_county_total = pd.read_sql(query, engine)
df_running_county_total

,county_code,county_name,region,respondent_count,running_total_respondents,cumulative_sample_percent
0,1,Mombasa,Coast,428,428.0,2.05
1,2,Kwale,Coast,377,805.0,3.86
2,3,Kilifi,Coast,530,1335.0,6.40
3,4,Tana River,Coast,333,1668.0,7.99
4,5,Lamu,Coast,258,1926.0,9.23
5,6,Taita Taveta,Coast,394,2320.0,11.12
6,7,Garissa,North Eastern,306,2626.0,12.58
7,8,Wajir,North Eastern,418,3044.0,14.58
8,9,Mandera,North Eastern,390,3434.0,16.45
9,10,Marsabit,Eastern,369,3803.0,18.22


The running total begins with Mombasa's `428` respondents and reaches `20,871` after Nairobi, confirming that the county-level counts add up to the full sample. The cumulative percentage reaches `100.00` percent at county `47`.

The same pattern could be used to calculate cumulative access coverage by ranking counties from highest to lowest exclusion, helping NGOs or policymakers estimate how much of the target population is covered as they add priority counties to an intervention plan.


### 6. Respondent Literacy Position Within County

Respondent literacy scores are compared with county averages to show local gaps in financial knowledge. This supports targeted financial capability programming within counties.


In [24]:
# County literacy averages provide local context for respondent capability scores.
query = """
SELECT
    interview__key,
    county,
    county_name,
    "Sex",
    "Age",
    "Financial_literacy_index_fnl" AS respondent_financial_literacy_score,
    ROUND(
        AVG("Financial_literacy_index_fnl") OVER (PARTITION BY county)::numeric,
        2
    ) AS county_avg_financial_literacy_score,
    CASE
        WHEN "Financial_literacy_index_fnl" > AVG("Financial_literacy_index_fnl") OVER (PARTITION BY county) THEN 'Above county average'
        WHEN "Financial_literacy_index_fnl" < AVG("Financial_literacy_index_fnl") OVER (PARTITION BY county) THEN 'Below county average'
        ELSE 'Equal to county average'
    END AS literacy_position_within_county
FROM finaccess_clean
ORDER BY county, interview__key
LIMIT 50;
"""

df_literacy_window_comparison = pd.read_sql(query, engine)
df_literacy_window_comparison

,interview__key,county,county_name,Sex,Age,respondent_financial_literacy_score,county_avg_financial_literacy_score,literacy_position_within_county
0,00-63-65-16,1,Mombasa,1.0,6.0,1.0,1.56,Below county average
1,01-04-67-96,1,Mombasa,2.0,3.0,1.0,1.56,Below county average
2,01-45-35-12,1,Mombasa,2.0,3.0,1.0,1.56,Below county average
3,01-54-54-81,1,Mombasa,1.0,6.0,1.0,1.56,Below county average
4,01-64-65-55,1,Mombasa,1.0,1.0,2.0,1.56,Above county average
5,01-77-26-23,1,Mombasa,1.0,3.0,1.0,1.56,Below county average
6,01-81-58-24,1,Mombasa,2.0,2.0,2.0,1.56,Above county average
7,01-90-44-38,1,Mombasa,2.0,3.0,1.0,1.56,Below county average
8,02-14-38-73,1,Mombasa,1.0,2.0,2.0,1.56,Above county average
9,02-25-61-12,1,Mombasa,2.0,6.0,2.0,1.56,Above county average


The sample output shows Mombasa respondents with their individual financial literacy score, the Mombasa county average of about `1.56`, and an above-or-below county average flag. Some respondents with scores of `2` or `3` are above the county average, while many respondents with a score of `1` are below it.

This window-function pattern is highly relevant for inclusion targeting. It can identify within-county variation that a county average hides. For NGOs, this supports more precise financial capability programming. For fintechs, it suggests that product education and onboarding support may need to be tailored even within the same county.


### 7. Peer County Comparisons

Adjacent county comparisons in the ranking show how close each county is to the counties immediately above and below it. This helps distinguish small performance gaps from deeper structural differences.


In [25]:
# Peer comparisons show whether counties are close to or far from adjacent performers.
query = """
WITH county_access AS (
    SELECT
        cr.county_code,
        cr.county_name,
        cr.region,
        COUNT(*) AS respondent_count,
        AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS overall_access_rate_percent
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    GROUP BY cr.county_code, cr.county_name, cr.region
),
ordered_counties AS (
    SELECT
        county_code,
        county_name,
        region,
        respondent_count,
        overall_access_rate_percent,
        LAG(county_name) OVER (ORDER BY overall_access_rate_percent DESC) AS previous_higher_county,
        LAG(overall_access_rate_percent) OVER (ORDER BY overall_access_rate_percent DESC) AS previous_higher_rate,
        LEAD(county_name) OVER (ORDER BY overall_access_rate_percent DESC) AS next_lower_county,
        LEAD(overall_access_rate_percent) OVER (ORDER BY overall_access_rate_percent DESC) AS next_lower_rate
    FROM county_access
)
SELECT
    county_code,
    county_name,
    region,
    respondent_count,
    ROUND(overall_access_rate_percent::numeric, 2) AS overall_access_rate_percent,
    previous_higher_county,
    ROUND(previous_higher_rate::numeric, 2) AS previous_higher_rate,
    next_lower_county,
    ROUND(next_lower_rate::numeric, 2) AS next_lower_rate
FROM ordered_counties
ORDER BY overall_access_rate_percent DESC;
"""

df_lag_lead_county_access = pd.read_sql(query, engine)
df_lag_lead_county_access

,county_code,county_name,region,respondent_count,overall_access_rate_percent,previous_higher_county,previous_higher_rate,next_lower_county,next_lower_rate
0,47,Nairobi,Nairobi,622,93.73,None,NaN,Nyeri,92.12
1,19,Nyeri,Central,457,92.12,Nairobi,93.73,Kirinyaga,91.54
2,20,Kirinyaga,Central,508,91.54,Nyeri,92.12,Embu,90.17
3,14,Embu,Eastern,478,90.17,Kirinyaga,91.54,Kiambu,89.65
4,22,Kiambu,Central,541,89.65,Embu,90.17,Taita Taveta,86.80
5,6,Taita Taveta,Coast,394,86.80,Kiambu,89.65,Nandi,86.74
6,29,Nandi,Rift Valley,475,86.74,Taita Taveta,86.80,Nyandarua,86.48
7,18,Nyandarua,Central,429,86.48,Nandi,86.74,Laikipia,86.47
8,31,Laikipia,Rift Valley,377,86.47,Nyandarua,86.48,Elgeyo-Marakwet,85.92
9,28,Elgeyo-Marakwet,Rift Valley,426,85.92,Laikipia,86.47,Nyamira,85.71


The result places Nairobi at the top, with no previous higher county and Nyeri as the next lower county. Nyeri then shows Nairobi as the previous higher county and Kirinyaga as the next lower county. At the bottom, West Pokot has Turkana as the previous higher county and no next lower county.

This neighbouring comparison reveals the spacing of county performance. Some counties are close to their immediate peers, while others have larger gaps. For targeting, this helps distinguish between counties that need modest improvement to catch up with their peers and counties that may require deeper structural support.


### 8. Regional Best and Weakest Performers

Regional best-and-weakest comparisons show that variation exists even within broad regions. This supports county-specific targeting rather than assuming all counties in a region face the same access constraints.


In [26]:
# Regional best and weakest performers identify localised strengths and gaps.
query = """
WITH county_indicator_rates AS (
    SELECT
        cr.region,
        cr.county_name,
        AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS mobile_money_use_rate_percent,
        AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS bank_use_rate_percent,
        AVG(CASE WHEN fm."Savings_usage" = 1 THEN 1.0 WHEN fm."Savings_usage" IS NULL THEN NULL ELSE 0.0 END) * 100 AS savings_usage_rate_percent,
        AVG(CASE WHEN fm."Loan_usage" = 1 THEN 1.0 WHEN fm."Loan_usage" IS NULL THEN NULL ELSE 0.0 END) * 100 AS loan_usage_rate_percent,
        AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS overall_access_rate_percent
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    GROUP BY cr.region, cr.county_name
),
indicator_long AS (
    SELECT region, county_name, 'Mobile money use' AS indicator_name, mobile_money_use_rate_percent AS indicator_rate FROM county_indicator_rates
    UNION ALL SELECT region, county_name, 'Bank use', bank_use_rate_percent FROM county_indicator_rates
    UNION ALL SELECT region, county_name, 'Savings use', savings_usage_rate_percent FROM county_indicator_rates
    UNION ALL SELECT region, county_name, 'Loan use', loan_usage_rate_percent FROM county_indicator_rates
    UNION ALL SELECT region, county_name, 'Overall access', overall_access_rate_percent FROM county_indicator_rates
),
regional_extremes AS (
    SELECT
        region,
        indicator_name,
        FIRST_VALUE(county_name) OVER (
            PARTITION BY region, indicator_name
            ORDER BY indicator_rate DESC, county_name
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS best_county,
        FIRST_VALUE(indicator_rate) OVER (
            PARTITION BY region, indicator_name
            ORDER BY indicator_rate DESC, county_name
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS best_county_rate,
        LAST_VALUE(county_name) OVER (
            PARTITION BY region, indicator_name
            ORDER BY indicator_rate DESC, county_name
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS worst_county,
        LAST_VALUE(indicator_rate) OVER (
            PARTITION BY region, indicator_name
            ORDER BY indicator_rate DESC, county_name
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS worst_county_rate
    FROM indicator_long
)
SELECT DISTINCT
    region,
    indicator_name,
    best_county,
    ROUND(best_county_rate::numeric, 2) AS best_county_rate_percent,
    worst_county,
    ROUND(worst_county_rate::numeric, 2) AS worst_county_rate_percent
FROM regional_extremes
ORDER BY region, indicator_name;
"""

df_regional_best_worst = pd.read_sql(query, engine)
df_regional_best_worst

,region,indicator_name,best_county,best_county_rate_percent,worst_county,worst_county_rate_percent
0,Central,Bank use,Kiambu,66.98,Murang'a,45.74
1,Central,Loan use,Kiambu,74.86,Kirinyaga,56.50
2,Central,Mobile money use,Nyeri,89.93,Murang'a,78.49
3,Central,Overall access,Nyeri,92.12,Murang'a,82.36
4,Central,Savings use,Kiambu,78.19,Murang'a,59.50
5,Coast,Bank use,Taita Taveta,54.57,Tana River,23.12
6,Coast,Loan use,Taita Taveta,63.96,Lamu,29.07
7,Coast,Mobile money use,Taita Taveta,86.29,Tana River,70.27
8,Coast,Overall access,Taita Taveta,86.80,Tana River,70.87
9,Coast,Savings use,Kwale,67.90,Tana River,18.92


The regional best-and-worst table shows meaningful variation inside regions. In Central, Kiambu leads on bank use, loan use, and savings use, while Nyeri leads on mobile money and overall access. In Coast, Taita Taveta leads on several indicators, while Tana River is the weakest on bank use, mobile money use, overall access, and savings use. In Rift Valley, Uasin Gishu leads on bank use, Laikipia leads on mobile money use, Nandi leads on overall access and loan use, and West Pokot is the weakest on several indicators.

This reveals that regional averages can hide large internal differences. For targeting opportunities, the best county in a region can be studied for enabling conditions, while the worst county can become a priority for intervention. Fintechs can use this to design region-specific expansion strategies, and NGOs can use it to target financial capability, savings, credit, and inclusion interventions where the regional gap is largest.


## Section 7: Reusable Reporting Assets

This section creates reusable county summaries, exclusion tables, gender gap outputs, and scorecards. These assets support consistent reporting and reduce the risk of conflicting definitions across analyses.


### 1. County Financial Summary

The county financial summary provides one row per county with key access and product-usage indicators. It is the primary reporting table for county-level inclusion comparisons.


In [27]:
# Stable county indicators support reporting and dashboard outputs.
from sqlalchemy import text

query = """
CREATE OR REPLACE VIEW county_financial_summary AS
SELECT
    cr.county_code,
    cr.county_name,
    cr.region,
    COUNT(*) AS respondent_count,
    ROUND((AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS mobile_money_rate,
    ROUND((AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS bank_rate,
    ROUND((AVG(CASE WHEN fm."Savings_usage" = 1 THEN 1.0 WHEN fm."Savings_usage" IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS savings_rate,
    ROUND((AVG(CASE WHEN fm."Loan_usage" = 1 THEN 1.0 WHEN fm."Loan_usage" IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS loan_rate,
    ROUND((AVG(CASE WHEN fm."All_Insurance_including_NHIF" = 1 THEN 1.0 WHEN fm."All_Insurance_including_NHIF" IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS insurance_rate,
    ROUND((AVG(CASE WHEN fm."Informal_usage" = 1 THEN 1.0 WHEN fm."Informal_usage" IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS informal_rate,
    ROUND((AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 WHEN fm."Overall_Access_fnl" IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS overall_access_rate
FROM finaccess_master fm
INNER JOIN county_reference cr
    ON CAST(fm.county AS INTEGER) = cr.county_code
GROUP BY cr.county_code, cr.county_name, cr.region;
"""

with engine.begin() as conn:
    conn.execute(text(query))

check_query = """
SELECT *
FROM county_financial_summary
ORDER BY overall_access_rate DESC
LIMIT 10;
"""

df_county_financial_summary_check = pd.read_sql(check_query, engine)
df_county_financial_summary_check

,county_code,county_name,region,respondent_count,mobile_money_rate,bank_rate,savings_rate,loan_rate,insurance_rate,informal_rate,overall_access_rate
0,47,Nairobi,Nairobi,622,92.93,72.99,87.14,63.83,33.76,48.23,93.73
1,19,Nyeri,Central,457,89.93,59.30,67.61,64.11,28.23,48.80,92.12
2,20,Kirinyaga,Central,508,86.22,55.71,73.23,56.50,31.50,40.75,91.54
3,14,Embu,Eastern,478,87.03,54.18,75.94,67.57,34.94,50.00,90.17
4,22,Kiambu,Central,541,86.11,66.98,78.19,74.86,32.90,56.93,89.65
5,6,Taita Taveta,Coast,394,86.29,54.57,55.33,63.96,18.27,51.02,86.80
6,29,Nandi,Rift Valley,475,81.68,59.58,74.32,72.63,17.89,48.42,86.74
7,18,Nyandarua,Central,429,83.68,49.18,67.37,68.76,25.17,62.70,86.48
8,31,Laikipia,Rift Valley,377,84.62,49.60,68.17,59.95,27.06,50.93,86.47
9,28,Elgeyo-Marakwet,Rift Valley,426,83.80,53.99,78.17,72.54,24.65,58.69,85.92


The view creates one row per county and exposes the main financial inclusion indicators in a clean reporting format. In the validation run, Nairobi appears at the top by overall access, followed by counties such as Nyeri, Kirinyaga, Embu, and Kiambu.

For analysis and dashboarding, this view becomes a reusable county summary layer. A fintech could connect it to a market prioritisation dashboard. An NGO or development organisation could use it to compare county-level access, savings, loans, insurance, and informal finance patterns without rewriting aggregation logic.


### 2. County Exclusion Analysis

The exclusion analysis ranks counties by exclusion risk and classifies them into practical priority groups. This is directly relevant for public-sector targeting and development programming.


In [28]:
# Exclusion-focused summary directs attention to counties with highest intervention need.
query = """
CREATE OR REPLACE VIEW financial_exclusion_analysis AS
WITH county_exclusion AS (
    SELECT
        cr.county_code,
        cr.county_name,
        cr.region,
        COUNT(*) AS respondent_count,
        SUM(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 0 ELSE 1 END) AS excluded_respondents,
        ROUND((AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS overall_access_rate,
        ROUND((100 - AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS exclusion_rate
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    GROUP BY cr.county_code, cr.county_name, cr.region
)
SELECT
    RANK() OVER (ORDER BY exclusion_rate DESC) AS exclusion_rank,
    county_code,
    county_name,
    region,
    respondent_count,
    excluded_respondents,
    overall_access_rate,
    exclusion_rate,
    CASE
        WHEN exclusion_rate >= 25 THEN 'High Exclusion'
        WHEN exclusion_rate >= 15 THEN 'Medium Exclusion'
        ELSE 'Low Exclusion'
    END AS exclusion_classification
FROM county_exclusion;
"""

with engine.begin() as conn:
    conn.execute(text(query))

check_query = """
SELECT *
FROM financial_exclusion_analysis
ORDER BY exclusion_rank
LIMIT 10;
"""

df_financial_exclusion_check = pd.read_sql(check_query, engine)
df_financial_exclusion_check

,exclusion_rank,county_code,county_name,region,respondent_count,excluded_respondents,overall_access_rate,exclusion_rate,exclusion_classification
0,1,24,West Pokot,Rift Valley,375,191,49.07,50.93,High Exclusion
1,2,23,Turkana,Rift Valley,400,139,65.25,34.75,High Exclusion
2,3,4,Tana River,Coast,333,97,70.87,29.13,High Exclusion
3,4,33,Narok,Rift Valley,406,113,72.17,27.83,High Exclusion
4,5,44,Migori,Nyanza,531,144,72.88,27.12,High Exclusion
5,6,37,Kakamega,Western,601,157,73.88,26.12,High Exclusion
6,7,41,Siaya,Nyanza,441,114,74.15,25.85,High Exclusion
7,8,40,Busia,Western,399,102,74.44,25.56,High Exclusion
8,9,30,Baringo,Rift Valley,383,97,74.67,25.33,High Exclusion
9,10,3,Kilifi,Coast,530,131,75.28,24.72,Medium Exclusion


The exclusion view highlights counties with the highest exclusion risk. In the validation run, West Pokot has the highest exclusion rate at `50.93%`, followed by Turkana, Tana River, Narok, and Migori. These counties are classified as high exclusion under the working thresholds.

The analytical value is clear: this view converts a broad financial inclusion dataset into a prioritisation list. Development organisations can use it to identify counties for deeper field investigation, while fintechs can use it to distinguish markets that may need basic access-building work from markets ready for more advanced products.


### 3. County Gender Gap Analysis

The gender gap table highlights where mobile money and bank-use differences are largest within counties. This supports gender-sensitive policy, outreach, and product design.


In [29]:
# Gender gap summary surfaces counties where product access differs by respondent group.
query = """
CREATE OR REPLACE VIEW gender_financial_gap AS
SELECT
    cr.county_code,
    cr.county_name,
    cr.region,
    COUNT(*) AS respondent_count,
    ROUND((AVG(CASE WHEN fm."Sex" = 1 THEN CASE WHEN fm.mobile_money_use = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS male_mobile_money_rate,
    ROUND((AVG(CASE WHEN fm."Sex" = 2 THEN CASE WHEN fm.mobile_money_use = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS female_mobile_money_rate,
    ROUND(((AVG(CASE WHEN fm."Sex" = 1 THEN CASE WHEN fm.mobile_money_use = 1 THEN 1.0 ELSE 0.0 END END) - AVG(CASE WHEN fm."Sex" = 2 THEN CASE WHEN fm.mobile_money_use = 1 THEN 1.0 ELSE 0.0 END END)) * 100)::numeric, 2) AS mobile_money_gender_gap,
    ROUND((AVG(CASE WHEN fm."Sex" = 1 THEN CASE WHEN fm.bank_use = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS male_bank_rate,
    ROUND((AVG(CASE WHEN fm."Sex" = 2 THEN CASE WHEN fm.bank_use = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS female_bank_rate,
    ROUND(((AVG(CASE WHEN fm."Sex" = 1 THEN CASE WHEN fm.bank_use = 1 THEN 1.0 ELSE 0.0 END END) - AVG(CASE WHEN fm."Sex" = 2 THEN CASE WHEN fm.bank_use = 1 THEN 1.0 ELSE 0.0 END END)) * 100)::numeric, 2) AS bank_gender_gap
FROM finaccess_master fm
INNER JOIN county_reference cr
    ON CAST(fm.county AS INTEGER) = cr.county_code
GROUP BY cr.county_code, cr.county_name, cr.region;
"""

with engine.begin() as conn:
    conn.execute(text(query))

check_query = """
SELECT *
FROM gender_financial_gap
ORDER BY ABS(bank_gender_gap) DESC
LIMIT 10;
"""

df_gender_gap_check = pd.read_sql(check_query, engine)
df_gender_gap_check

,county_code,county_name,region,respondent_count,male_mobile_money_rate,female_mobile_money_rate,mobile_money_gender_gap,male_bank_rate,female_bank_rate,bank_gender_gap
0,7,Garissa,North Eastern,306,81.19,81.46,-0.28,39.60,16.59,23.02
1,44,Migori,Nyanza,531,75.96,65.94,10.02,52.40,30.34,22.06
2,23,Turkana,Rift Valley,400,71.31,61.87,9.44,38.52,16.91,21.62
3,33,Narok,Rift Valley,406,70.32,68.53,1.80,51.61,31.08,20.54
4,1,Mombasa,Coast,428,85.06,77.56,7.50,64.37,44.49,19.88
5,2,Kwale,Coast,377,83.03,80.19,2.84,48.48,31.60,16.88
6,36,Bomet,Rift Valley,530,79.22,77.26,1.96,59.31,43.14,16.16
7,45,Kisii,Nyanza,503,80.50,85.15,-4.65,57.00,40.92,16.08
8,26,Trans Nzoia,Rift Valley,162,81.16,69.89,11.27,62.32,47.31,15.01
9,32,Nakuru,Rift Valley,572,82.52,80.06,2.46,61.79,47.55,14.24


The view returns one row per county and surfaces where gender differences are largest. Sorting by the absolute bank gender gap helps identify counties where formal financial access differs most sharply between male-coded and female-coded respondents.

For policy and product teams, this is more actionable than a national gender gap alone. A county-level gender gap view can guide localised product design, agent outreach, women's financial capability programmes, and monitoring of inclusive finance outcomes.


### 4. County Scorecard

The county scorecard combines access, exclusion, financial health, vulnerability, and literacy indicators. It provides a compact county performance table for reporting and dashboarding.


In [30]:
# Stored county scorecard supports repeated reporting without recalculating metrics.
query = """
DROP MATERIALIZED VIEW IF EXISTS county_scorecard;

CREATE MATERIALIZED VIEW county_scorecard AS
WITH health_scores AS (
    SELECT
        CAST(county AS INTEGER) AS county_code,
        ROUND(AVG(finhealth_fnl)::numeric, 2) AS avg_finhealth_fnl,
        ROUND(AVG(vul_index_fnl)::numeric, 2) AS avg_vul_index_fnl,
        ROUND(AVG("Financial_literacy_index_fnl")::numeric, 2) AS avg_financial_literacy_index_fnl
    FROM finaccess_master
    GROUP BY CAST(county AS INTEGER)
)
SELECT
    cfs.county_code,
    cfs.county_name,
    cfs.region,
    cfs.respondent_count,
    cfs.mobile_money_rate,
    cfs.bank_rate,
    cfs.savings_rate,
    cfs.loan_rate,
    cfs.insurance_rate,
    cfs.informal_rate,
    cfs.overall_access_rate,
    ROUND((100 - cfs.overall_access_rate)::numeric, 2) AS exclusion_rate,
    hs.avg_finhealth_fnl,
    hs.avg_vul_index_fnl,
    hs.avg_financial_literacy_index_fnl
FROM county_financial_summary cfs
INNER JOIN health_scores hs
    ON cfs.county_code = hs.county_code;

CREATE INDEX IF NOT EXISTS idx_county_scorecard_county_code
ON county_scorecard (county_code);
"""

with engine.begin() as conn:
    conn.execute(text(query))

check_query = """
SELECT *
FROM county_scorecard
ORDER BY overall_access_rate DESC
LIMIT 10;
"""

df_county_scorecard_check = pd.read_sql(check_query, engine)
df_county_scorecard_check

,county_code,county_name,region,respondent_count,mobile_money_rate,bank_rate,savings_rate,loan_rate,insurance_rate,informal_rate,overall_access_rate,exclusion_rate,avg_finhealth_fnl,avg_vul_index_fnl,avg_financial_literacy_index_fnl
0,47,Nairobi,Nairobi,622,92.93,72.99,87.14,63.83,33.76,48.23,93.73,6.27,0.36,2.64,1.95
1,19,Nyeri,Central,457,89.93,59.30,67.61,64.11,28.23,48.80,92.12,7.88,0.17,2.56,1.75
2,20,Kirinyaga,Central,508,86.22,55.71,73.23,56.50,31.50,40.75,91.54,8.46,0.20,2.74,1.98
3,14,Embu,Eastern,478,87.03,54.18,75.94,67.57,34.94,50.00,90.17,9.83,0.18,2.65,1.98
4,22,Kiambu,Central,541,86.11,66.98,78.19,74.86,32.90,56.93,89.65,10.35,0.23,2.61,1.44
5,6,Taita Taveta,Coast,394,86.29,54.57,55.33,63.96,18.27,51.02,86.80,13.20,0.22,2.38,1.78
6,29,Nandi,Rift Valley,475,81.68,59.58,74.32,72.63,17.89,48.42,86.74,13.26,0.13,2.53,1.76
7,18,Nyandarua,Central,429,83.68,49.18,67.37,68.76,25.17,62.70,86.48,13.52,0.16,2.38,1.65
8,31,Laikipia,Rift Valley,377,84.62,49.60,68.17,59.95,27.06,50.93,86.47,13.53,0.21,2.52,1.78
9,28,Elgeyo-Marakwet,Rift Valley,426,83.80,53.99,78.17,72.54,24.65,58.69,85.92,14.08,0.16,2.60,1.66


`county_scorecard` produces a compact, reusable county performance table with access rates, exclusion rates, financial health, vulnerability, and financial literacy measures. This is suitable for downstream charting, ranking, and export to BI tools.

The materialized view also receives an index on `county_code`, which supports faster lookup when the scorecard is joined to other county-level tables or filtered by county. This is an example of combining analytical modelling with database performance design.


### 5. County Index Check

The county index supports faster county-based filtering and joins in the raw demographics table. It improves analysis performance without changing the underlying results.


In [31]:
# Faster geographic filtering supports repeated county-level analysis.
query = """
CREATE INDEX IF NOT EXISTS idx_finaccess_part1_county
ON finaccess_part1 (county);
"""

with engine.begin() as conn:
    conn.execute(text(query))

check_query = """
SELECT
    indexname,
    indexdef
FROM pg_indexes
WHERE tablename = 'finaccess_part1'
  AND indexname = 'idx_finaccess_part1_county';
"""

df_county_index_check = pd.read_sql(check_query, engine)
df_county_index_check

,indexname,indexdef
0,idx_finaccess_part1_county,CREATE INDEX idx_finaccess_part1_county ON pub...


The index check confirms that county-based access in `finaccess_part1` is supported by `idx_finaccess_part1_county`. This improves the responsiveness of repeated county-level analysis without changing any analytical result.


### 6. Inclusion and Exclusion Leaders

The scorecard identifies the strongest inclusion counties and the counties with the highest exclusion risk. These lists provide a concise starting point for stakeholder discussion.


In [32]:
# Scorecard output highlights strongest inclusion counties and highest-exclusion counties.
query = """
WITH ranked_scorecard AS (
    SELECT
        'Top 10 by overall financial inclusion' AS report_section,
        ROW_NUMBER() OVER (ORDER BY overall_access_rate DESC) AS rank_position,
        county_code,
        county_name,
        region,
        respondent_count,
        overall_access_rate,
        exclusion_rate,
        mobile_money_rate,
        bank_rate,
        avg_finhealth_fnl,
        avg_financial_literacy_index_fnl
    FROM county_scorecard
    UNION ALL
    SELECT
        'Bottom 10 by financial exclusion risk' AS report_section,
        ROW_NUMBER() OVER (ORDER BY exclusion_rate DESC) AS rank_position,
        county_code,
        county_name,
        region,
        respondent_count,
        overall_access_rate,
        exclusion_rate,
        mobile_money_rate,
        bank_rate,
        avg_finhealth_fnl,
        avg_financial_literacy_index_fnl
    FROM county_scorecard
)
SELECT *
FROM ranked_scorecard
WHERE rank_position <= 10
ORDER BY report_section, rank_position;
"""

df_scorecard_top_bottom = pd.read_sql(query, engine)
df_scorecard_top_bottom

,report_section,rank_position,county_code,county_name,region,respondent_count,overall_access_rate,exclusion_rate,mobile_money_rate,bank_rate,avg_finhealth_fnl,avg_financial_literacy_index_fnl
0,Bottom 10 by financial exclusion risk,1,24,West Pokot,Rift Valley,375,49.07,50.93,45.33,20.53,0.11,2.03
1,Bottom 10 by financial exclusion risk,2,23,Turkana,Rift Valley,400,65.25,34.75,64.75,23.50,0.01,2.12
2,Bottom 10 by financial exclusion risk,3,4,Tana River,Coast,333,70.87,29.13,70.27,23.12,0.05,1.95
3,Bottom 10 by financial exclusion risk,4,33,Narok,Rift Valley,406,72.17,27.83,69.38,39.01,0.15,1.79
4,Bottom 10 by financial exclusion risk,5,44,Migori,Nyanza,531,72.88,27.12,69.87,38.98,0.11,2.17
5,Bottom 10 by financial exclusion risk,6,37,Kakamega,Western,601,73.88,26.12,69.72,45.42,0.17,1.82
6,Bottom 10 by financial exclusion risk,7,41,Siaya,Nyanza,441,74.15,25.85,70.98,39.00,0.06,1.90
7,Bottom 10 by financial exclusion risk,8,40,Busia,Western,399,74.44,25.56,71.11,40.95,0.08,1.74
8,Bottom 10 by financial exclusion risk,9,30,Baringo,Rift Valley,383,74.67,25.33,66.32,39.69,0.10,1.86
9,Bottom 10 by financial exclusion risk,10,3,Kilifi,Coast,530,75.28,24.72,73.40,33.58,0.13,1.78


The scorecard returns Nairobi, Nyeri, Kirinyaga, Embu, and Kiambu among the strongest counties by overall inclusion. It also identifies West Pokot, Turkana, Tana River, Narok, and Migori among the highest-exclusion counties.

High-inclusion counties may support more advanced digital finance products, while high-exclusion counties may require foundational access, trust-building, financial capability, and infrastructure support.


### 7. Scorecard Maintenance Check

Refreshing the scorecard confirms that reporting outputs can be updated when underlying data changes. This keeps county summaries aligned with the current database state.


In [33]:
# Refresh and cleanup keep reporting outputs current and database objects easy to govern.
query = """
REFRESH MATERIALIZED VIEW county_scorecard;

CREATE OR REPLACE VIEW view_drop_demo AS
SELECT 'temporary demo view' AS note;

DROP VIEW IF EXISTS view_drop_demo;
"""

with engine.begin() as conn:
    conn.execute(text(query))

check_query = """
SELECT 'county_scorecard refreshed and demo view dropped safely' AS maintenance_status;
"""

df_view_maintenance_check = pd.read_sql(check_query, engine)
df_view_maintenance_check

,maintenance_status
0,county_scorecard refreshed and demo view dropp...


The maintenance check confirms that `county_scorecard` was refreshed and that temporary reporting objects were removed. This keeps the reporting layer current and reduces confusion from obsolete database objects.


### 8. National Inclusion Dashboard

The national dashboard condenses the main inclusion, exclusion, financial health, and gender-gap indicators into one reporting row. It is suitable for direct export into BI or reporting tools.


In [34]:
# National dashboard consolidates key indicators for executive reporting.
query = """
WITH national_rates AS (
    SELECT
        SUM(respondent_count) AS total_respondents,
        ROUND((SUM(mobile_money_rate * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_mobile_money_rate,
        ROUND((SUM(bank_rate * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_bank_rate,
        ROUND((SUM(savings_rate * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_savings_rate,
        ROUND((SUM(loan_rate * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_loan_rate,
        ROUND((SUM(insurance_rate * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_insurance_rate,
        ROUND((SUM(informal_rate * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_informal_rate,
        ROUND((SUM(overall_access_rate * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_overall_access_rate
    FROM county_financial_summary
),
scorecard_metrics AS (
    SELECT
        ROUND((SUM(avg_finhealth_fnl * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_avg_finhealth_fnl,
        ROUND((SUM(avg_vul_index_fnl * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_avg_vul_index_fnl,
        ROUND((SUM(avg_financial_literacy_index_fnl * respondent_count) / SUM(respondent_count))::numeric, 2) AS national_avg_financial_literacy_index_fnl
    FROM county_scorecard
),
top_inclusion AS (
    SELECT county_name AS top_inclusion_county, overall_access_rate AS top_inclusion_rate
    FROM county_scorecard
    ORDER BY overall_access_rate DESC
    LIMIT 1
),
highest_exclusion AS (
    SELECT county_name AS highest_exclusion_county, exclusion_rate AS highest_exclusion_rate, exclusion_classification
    FROM financial_exclusion_analysis
    ORDER BY exclusion_rate DESC
    LIMIT 1
),
gender_gap_summary AS (
    SELECT
        ROUND(AVG(mobile_money_gender_gap)::numeric, 2) AS avg_county_mobile_money_gender_gap,
        ROUND(AVG(bank_gender_gap)::numeric, 2) AS avg_county_bank_gender_gap
    FROM gender_financial_gap
)
SELECT
    'Kenya National Financial Inclusion Dashboard' AS dashboard_name,
    nr.total_respondents,
    nr.national_mobile_money_rate,
    nr.national_bank_rate,
    nr.national_savings_rate,
    nr.national_loan_rate,
    nr.national_insurance_rate,
    nr.national_informal_rate,
    nr.national_overall_access_rate,
    ROUND((100 - nr.national_overall_access_rate)::numeric, 2) AS national_exclusion_rate,
    sm.national_avg_finhealth_fnl,
    sm.national_avg_vul_index_fnl,
    sm.national_avg_financial_literacy_index_fnl,
    ggs.avg_county_mobile_money_gender_gap,
    ggs.avg_county_bank_gender_gap,
    ti.top_inclusion_county,
    ti.top_inclusion_rate,
    he.highest_exclusion_county,
    he.highest_exclusion_rate,
    he.exclusion_classification
FROM national_rates nr
CROSS JOIN scorecard_metrics sm
CROSS JOIN top_inclusion ti
CROSS JOIN highest_exclusion he
CROSS JOIN gender_gap_summary ggs;
"""

df_national_dashboard = pd.read_sql(query, engine)
df_national_dashboard

,dashboard_name,total_respondents,national_mobile_money_rate,national_bank_rate,national_savings_rate,national_loan_rate,national_insurance_rate,national_informal_rate,national_overall_access_rate,national_exclusion_rate,national_avg_finhealth_fnl,national_avg_vul_index_fnl,national_avg_financial_literacy_index_fnl,avg_county_mobile_money_gender_gap,avg_county_bank_gender_gap,top_inclusion_county,top_inclusion_rate,highest_exclusion_county,highest_exclusion_rate,exclusion_classification
0,Kenya National Financial Inclusion Dashboard,20871.0,78.69,45.52,63.45,61.21,19.25,49.03,81.43,18.57,0.15,2.45,1.85,-0.2,10.03,Nairobi,93.73,West Pokot,50.93,High Exclusion


The dashboard result returns a single national reporting row. The validation run showed `20,871` respondents, `78.69%` mobile money use, `45.52%` bank use, `81.43%` overall access, and `18.57%` national exclusion.

Nairobi appears as the top inclusion county, while West Pokot appears as the highest-exclusion county under the working definition.


## Section 8: National Analytical Summary

The final section brings together county, gender, income, financial health, and geographic results. The combined outputs tell a coherent story of broad mobile money reach alongside persistent inequality.


### 1. Comprehensive County Scorecard

The county scorecard ranks all 47 counties using access, product usage, exclusion, financial health, vulnerability, and literacy indicators. This provides a consolidated view of county-level inclusion performance.


In [35]:
# Master scorecard combines county demographics, access, health, exclusion, and regional context.
master_scorecard_query = """
WITH county_demographics AS (
    SELECT
        CAST(fm.county AS INTEGER) AS county_code,
        COUNT(*) AS respondent_count,
        ROUND(AVG(fm."Age")::numeric, 2) AS avg_age_code,
        ROUND((AVG(CASE WHEN fm."Age" BETWEEN 2 AND 5 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS working_age_share,
        ROUND((AVG(CASE WHEN fm."Sex" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS male_share,
        ROUND((AVG(CASE WHEN fm."Sex" = 2 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS female_share,
        ROUND(AVG(fm."Education")::numeric, 2) AS avg_education_code,
        ROUND((AVG(CASE WHEN fm."Education" IN (3, 4, 5) THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS upper_education_share
    FROM finaccess_master fm
    GROUP BY CAST(fm.county AS INTEGER)
),
financial_access_rates AS (
    SELECT
        CAST(fm.county AS INTEGER) AS county_code,
        ROUND((AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS mobile_money_rate,
        ROUND((AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS bank_rate,
        ROUND((AVG(CASE WHEN fm."Savings_usage" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS savings_rate,
        ROUND((AVG(CASE WHEN fm."Loan_usage" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS loan_rate,
        ROUND((AVG(CASE WHEN fm."All_Insurance_including_NHIF" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS insurance_rate,
        ROUND((AVG(CASE WHEN fm."Informal_usage" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS informal_rate,
        ROUND((AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS overall_access_rate
    FROM finaccess_master fm
    GROUP BY CAST(fm.county AS INTEGER)
),
financial_health_scores AS (
    SELECT
        CAST(fm.county AS INTEGER) AS county_code,
        ROUND(AVG(fm.finhealth_fnl)::numeric, 2) AS avg_finhealth_fnl,
        ROUND(AVG(fm.vul_index_fnl)::numeric, 2) AS avg_vul_index_fnl,
        ROUND(AVG(fm."Financial_literacy_index_fnl")::numeric, 2) AS avg_financial_literacy_index_fnl
    FROM finaccess_master fm
    GROUP BY CAST(fm.county AS INTEGER)
),
exclusion_analysis AS (
    SELECT
        CAST(fm.county AS INTEGER) AS county_code,
        SUM(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 0 ELSE 1 END) AS excluded_respondents,
        ROUND((100 - AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS exclusion_rate
    FROM finaccess_master fm
    GROUP BY CAST(fm.county AS INTEGER)
),
regional_benchmarks AS (
    SELECT
        cr.region,
        ROUND((AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS regional_mobile_money_rate,
        ROUND((AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS regional_bank_rate,
        ROUND((AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS regional_overall_access_rate,
        ROUND(AVG(fm.finhealth_fnl)::numeric, 2) AS regional_avg_finhealth_fnl
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    GROUP BY cr.region
)
SELECT
    cr.county_code,
    cr.county_name,
    cr.region,
    cd.respondent_count,
    cd.avg_age_code,
    cd.working_age_share,
    cd.male_share,
    cd.female_share,
    cd.avg_education_code,
    cd.upper_education_share,
    far.mobile_money_rate,
    far.bank_rate,
    far.savings_rate,
    far.loan_rate,
    far.insurance_rate,
    far.informal_rate,
    far.overall_access_rate,
    ea.excluded_respondents,
    ea.exclusion_rate,
    fhs.avg_finhealth_fnl,
    fhs.avg_vul_index_fnl,
    fhs.avg_financial_literacy_index_fnl,
    rb.regional_mobile_money_rate,
    rb.regional_bank_rate,
    rb.regional_overall_access_rate,
    ROUND((far.overall_access_rate - rb.regional_overall_access_rate)::numeric, 2) AS overall_access_vs_region_points,
    ROUND(((far.mobile_money_rate + far.bank_rate + far.savings_rate + far.loan_rate + far.insurance_rate + far.overall_access_rate) / 6.0)::numeric, 2) AS composite_inclusion_score,
    RANK() OVER (ORDER BY ((far.mobile_money_rate + far.bank_rate + far.savings_rate + far.loan_rate + far.insurance_rate + far.overall_access_rate) / 6.0) DESC) AS composite_inclusion_rank
FROM county_demographics cd
INNER JOIN financial_access_rates far ON cd.county_code = far.county_code
INNER JOIN financial_health_scores fhs ON cd.county_code = fhs.county_code
INNER JOIN exclusion_analysis ea ON cd.county_code = ea.county_code
INNER JOIN county_reference cr ON cd.county_code = cr.county_code
INNER JOIN regional_benchmarks rb ON cr.region = rb.region
ORDER BY composite_inclusion_rank;
"""

df_final_county_scorecard = pd.read_sql(master_scorecard_query, engine)
df_final_county_scorecard

,county_code,county_name,region,respondent_count,avg_age_code,working_age_share,male_share,female_share,avg_education_code,upper_education_share,...,exclusion_rate,avg_finhealth_fnl,avg_vul_index_fnl,avg_financial_literacy_index_fnl,regional_mobile_money_rate,regional_bank_rate,regional_overall_access_rate,overall_access_vs_region_points,composite_inclusion_score,composite_inclusion_rank
0,47,Nairobi,Nairobi,622,3.26,91.48,43.89,56.11,3.08,78.62,...,6.27,0.36,2.64,1.95,92.93,72.99,93.73,0.00,74.06,1
1,22,Kiambu,Central,541,3.68,77.45,51.39,48.61,2.80,62.11,...,10.35,0.23,2.61,1.44,84.82,55.61,88.41,1.24,71.45,2
2,14,Embu,Eastern,478,4.09,72.38,45.40,54.60,2.70,53.77,...,9.83,0.18,2.65,1.98,81.24,46.36,83.96,6.21,68.31,3
3,19,Nyeri,Central,457,4.02,74.40,38.95,61.05,2.77,63.46,...,7.88,0.17,2.56,1.75,84.82,55.61,88.41,3.71,66.88,4
4,28,Elgeyo-Marakwet,Rift Valley,426,3.68,79.34,42.49,57.51,2.69,55.16,...,14.08,0.16,2.60,1.66,75.32,46.65,78.43,7.49,66.51,5
5,20,Kirinyaga,Central,508,4.11,73.82,37.99,62.01,2.71,57.28,...,8.46,0.20,2.74,1.98,84.82,55.61,88.41,3.13,65.78,6
6,29,Nandi,Rift Valley,475,3.66,77.89,42.53,57.47,2.61,49.47,...,13.26,0.13,2.53,1.76,75.32,46.65,78.43,8.31,65.47,7
7,34,Kajiado,Rift Valley,412,3.45,88.35,38.11,61.89,2.59,59.22,...,17.96,0.28,2.50,2.33,75.32,46.65,78.43,3.61,65.13,8
8,12,Meru,Eastern,637,3.74,76.77,46.31,53.69,2.56,48.19,...,15.38,0.07,2.24,1.67,81.24,46.36,83.96,0.66,65.02,9
9,27,Uasin Gishu,Rift Valley,551,3.36,81.13,45.55,54.45,2.90,69.15,...,14.70,0.15,2.63,1.56,75.32,46.65,78.43,6.87,64.67,10


The master scorecard produces one row for each of Kenya's 47 counties. In the validated output, Nairobi ranks first on the composite inclusion score, followed by Kiambu, Embu, Nyeri, and Elgeyo-Marakwet. This ranking reflects a broad definition of inclusion that combines mobile money, bank use, savings, loans, insurance, and overall access.

The scorecard also shows that inclusion is multidimensional. Some counties perform strongly on mobile money but less strongly on banking or insurance. Others have high savings or loan usage but lower overall access. This matters for Kenya's financial inclusion ecosystem because interventions should not assume that one indicator tells the whole story. Fintechs, NGOs, and development organisations need county-specific strategies that account for demographics, product use, financial health, and regional benchmarks together.


### 2. Gender Equity in Financial Access

Gender analysis compares overall access and bank access nationally and by county. This distinguishes broad national parity from local or product-specific gaps.


In [36]:
# Gender gap summary distinguishes national parity from local access differences.
query = """
WITH county_gender_rates AS (
    SELECT
        cr.county_code,
        cr.county_name,
        cr.region,
        ROUND((AVG(CASE WHEN fm."Sex" = 1 THEN CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS male_overall_access_rate,
        ROUND((AVG(CASE WHEN fm."Sex" = 2 THEN CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS female_overall_access_rate,
        ROUND(((AVG(CASE WHEN fm."Sex" = 1 THEN CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) - AVG(CASE WHEN fm."Sex" = 2 THEN CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END)) * 100)::numeric, 2) AS overall_access_gender_gap,
        ROUND(((AVG(CASE WHEN fm."Sex" = 1 THEN CASE WHEN fm.bank_use = 1 THEN 1.0 ELSE 0.0 END END) - AVG(CASE WHEN fm."Sex" = 2 THEN CASE WHEN fm.bank_use = 1 THEN 1.0 ELSE 0.0 END END)) * 100)::numeric, 2) AS bank_gender_gap
    FROM finaccess_master fm
    INNER JOIN county_reference cr ON CAST(fm.county AS INTEGER) = cr.county_code
    GROUP BY cr.county_code, cr.county_name, cr.region
),
national_gender_gap AS (
    SELECT
        ROUND((AVG(CASE WHEN "Sex" = 1 THEN CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS national_male_overall_access_rate,
        ROUND((AVG(CASE WHEN "Sex" = 2 THEN CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS national_female_overall_access_rate,
        ROUND(((AVG(CASE WHEN "Sex" = 1 THEN CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) - AVG(CASE WHEN "Sex" = 2 THEN CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END)) * 100)::numeric, 2) AS national_overall_access_gender_gap
    FROM finaccess_master
),
ranked_gaps AS (
    SELECT
        cgr.*,
        ROW_NUMBER() OVER (ORDER BY ABS(cgr.overall_access_gender_gap) DESC) AS largest_gap_rank,
        ROW_NUMBER() OVER (ORDER BY ABS(cgr.overall_access_gender_gap) ASC) AS smallest_gap_rank
    FROM county_gender_rates cgr
)
SELECT
    'Largest gender gaps' AS report_section,
    largest_gap_rank AS rank_position,
    county_name,
    region,
    male_overall_access_rate,
    female_overall_access_rate,
    overall_access_gender_gap,
    bank_gender_gap,
    ngg.national_male_overall_access_rate,
    ngg.national_female_overall_access_rate,
    ngg.national_overall_access_gender_gap
FROM ranked_gaps
CROSS JOIN national_gender_gap ngg
WHERE largest_gap_rank <= 10
UNION ALL
SELECT
    'Smallest gender gaps' AS report_section,
    smallest_gap_rank AS rank_position,
    county_name,
    region,
    male_overall_access_rate,
    female_overall_access_rate,
    overall_access_gender_gap,
    bank_gender_gap,
    ngg.national_male_overall_access_rate,
    ngg.national_female_overall_access_rate,
    ngg.national_overall_access_gender_gap
FROM ranked_gaps
CROSS JOIN national_gender_gap ngg
WHERE smallest_gap_rank <= 10
ORDER BY report_section, rank_position;
"""

df_gender_equity_summary = pd.read_sql(query, engine)
df_gender_equity_summary

,report_section,rank_position,county_name,region,male_overall_access_rate,female_overall_access_rate,overall_access_gender_gap,bank_gender_gap,national_male_overall_access_rate,national_female_overall_access_rate,national_overall_access_gender_gap
0,Largest gender gaps,1,West Pokot,Rift Valley,59.85,42.86,17.00,12.50,81.24,81.57,-0.33
1,Largest gender gaps,2,Vihiga,Western,69.44,81.92,-12.48,-2.01,81.24,81.57,-0.33
2,Largest gender gaps,3,Busia,Western,68.15,78.51,-10.36,1.96,81.24,81.57,-0.33
3,Largest gender gaps,4,Migori,Nyanza,78.37,69.35,9.02,22.06,81.24,81.57,-0.33
4,Largest gender gaps,5,Murang'a,Central,77.43,86.21,-8.77,0.50,81.24,81.57,-0.33
5,Largest gender gaps,6,Turkana,Rift Valley,71.31,62.59,8.72,21.62,81.24,81.57,-0.33
6,Largest gender gaps,7,Trans Nzoia,Rift Valley,81.16,73.12,8.04,15.01,81.24,81.57,-0.33
7,Largest gender gaps,8,Wajir,North Eastern,76.09,83.76,-7.67,12.41,81.24,81.57,-0.33
8,Largest gender gaps,9,Mombasa,Coast,87.36,79.92,7.44,19.88,81.24,81.57,-0.33
9,Largest gender gaps,10,Kajiado,Rift Valley,86.62,79.22,7.41,12.32,81.24,81.57,-0.33


The national overall access gender gap is small in the validated output: male-coded respondents have an overall access rate of `81.24%`, female-coded respondents have `81.57%`, and the national gap is `-0.33` percentage points. This suggests broad national parity on the overall access indicator.

However, county-level results reveal much larger local differences. West Pokot has the largest positive overall access gap at about `17.00` percentage points, while Vihiga and Busia show negative gaps where female-coded respondents have higher overall access than male-coded respondents. Bank gaps are also more pronounced than overall access gaps in several counties, which suggests that formal banking equity may require more targeted attention than general access.


### 3. Income Inequality in Access and Financial Health

Income quintile analysis shows how access, financial health, and vulnerability vary across welfare levels. This is central to assessing whether inclusion is reaching lower-income households.


In [37]:
# Income analysis shows whether access and wellbeing improve with household welfare.
query = """
WITH quintile_metrics AS (
    SELECT
        'National' AS geography_level,
        'Kenya' AS geography_name,
        CAST("Quintiles" AS INTEGER) AS income_quintile,
        COUNT(*) AS respondent_count,
        ROUND((AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS mobile_money_rate,
        ROUND((AVG(CASE WHEN bank_use = 1 THEN 1.0 WHEN bank_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS bank_rate,
        ROUND((AVG(CASE WHEN "Savings_usage" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS savings_rate,
        ROUND((AVG(CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS overall_access_rate,
        ROUND(AVG(finhealth_fnl)::numeric, 2) AS avg_finhealth_fnl,
        ROUND(AVG(vul_index_fnl)::numeric, 2) AS avg_vul_index_fnl
    FROM finaccess_master
    WHERE "Quintiles" IS NOT NULL
    GROUP BY CAST("Quintiles" AS INTEGER)
    UNION ALL
    SELECT
        'Region' AS geography_level,
        cr.region AS geography_name,
        CAST(fm."Quintiles" AS INTEGER) AS income_quintile,
        COUNT(*) AS respondent_count,
        ROUND((AVG(CASE WHEN fm.mobile_money_use = 1 THEN 1.0 WHEN fm.mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS mobile_money_rate,
        ROUND((AVG(CASE WHEN fm.bank_use = 1 THEN 1.0 WHEN fm.bank_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS bank_rate,
        ROUND((AVG(CASE WHEN fm."Savings_usage" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS savings_rate,
        ROUND((AVG(CASE WHEN fm."Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS overall_access_rate,
        ROUND(AVG(fm.finhealth_fnl)::numeric, 2) AS avg_finhealth_fnl,
        ROUND(AVG(fm.vul_index_fnl)::numeric, 2) AS avg_vul_index_fnl
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    WHERE fm."Quintiles" IS NOT NULL
    GROUP BY cr.region, CAST(fm."Quintiles" AS INTEGER)
)
SELECT *
FROM quintile_metrics
ORDER BY geography_level, geography_name, income_quintile;
"""

df_income_quintile_summary = pd.read_sql(query, engine)
df_income_quintile_summary

,geography_level,geography_name,income_quintile,respondent_count,mobile_money_rate,bank_rate,savings_rate,overall_access_rate,avg_finhealth_fnl,avg_vul_index_fnl
0,National,Kenya,1,4973,64.67,19.24,48.40,68.57,0.03,2.21
1,National,Kenya,2,4478,73.60,36.90,59.18,77.58,0.07,2.37
2,National,Kenya,3,4293,82.20,47.19,65.04,84.91,0.12,2.48
3,National,Kenya,4,4232,88.28,63.30,72.38,89.51,0.22,2.59
4,National,Kenya,5,2859,91.57,75.80,80.76,92.83,0.39,2.75
5,Region,Central,1,134,67.91,26.12,40.30,73.13,0.01,2.02
6,Region,Central,2,518,77.37,39.46,62.55,82.82,0.07,2.40
7,Region,Central,3,589,83.53,48.90,65.70,88.12,0.12,2.57
8,Region,Central,4,666,88.14,60.81,73.72,90.84,0.20,2.64
9,Region,Central,5,536,93.28,78.92,81.72,94.78,0.38,2.74


The national quintile results show a strong welfare gradient. Overall access rises from `68.57%` in quintile 1 to `92.83%` in quintile 5. Bank use rises even more sharply, from `19.24%` in quintile 1 to `75.80%` in quintile 5. Mobile money also rises, from `64.67%` to `91.57%`, but the bank gap is the most striking.

Financial health also improves across quintiles, from `0.03` in quintile 1 to `0.39` in quintile 5. This reinforces an important policy point: access and wellbeing are linked to economic position. Mobile money has broadened access, but lower-income groups remain less connected to formal banking and have weaker financial health outcomes.


### 4. Geographic Concentration of Exclusion

Geographic clusters identify areas where exclusion is spatially concentrated. This helps government and development partners target interventions beyond county averages.


In [38]:
# Geographic clustering identifies areas where exclusion may require spatial targeting.
query = """
WITH geo_points AS (
    SELECT
        cr.region,
        CAST(fm.county AS INTEGER) AS county_code,
        cr.county_name,
        fm."Latitude" AS latitude,
        fm."Longitude" AS longitude,
        CASE WHEN fm."Overall_Access_fnl" = 1 THEN 0 ELSE 1 END AS excluded_flag
    FROM finaccess_master fm
    INNER JOIN county_reference cr
        ON CAST(fm.county AS INTEGER) = cr.county_code
    WHERE fm."Latitude" IS NOT NULL
      AND fm."Longitude" IS NOT NULL
),
geo_clusters AS (
    SELECT
        FLOOR(latitude * 2) / 2.0 AS latitude_band,
        FLOOR(longitude * 2) / 2.0 AS longitude_band,
        MIN(region) AS dominant_region_sample,
        COUNT(*) AS respondent_count,
        COUNT(DISTINCT county_code) AS counties_in_cluster,
        ROUND(AVG(latitude)::numeric, 4) AS avg_latitude,
        ROUND(AVG(longitude)::numeric, 4) AS avg_longitude,
        SUM(excluded_flag) AS excluded_respondents,
        ROUND((AVG(excluded_flag) * 100)::numeric, 2) AS exclusion_rate
    FROM geo_points
    GROUP BY FLOOR(latitude * 2) / 2.0, FLOOR(longitude * 2) / 2.0
    HAVING COUNT(*) >= 50
)
SELECT
    latitude_band,
    longitude_band,
    dominant_region_sample,
    respondent_count,
    counties_in_cluster,
    avg_latitude,
    avg_longitude,
    excluded_respondents,
    exclusion_rate,
    RANK() OVER (ORDER BY exclusion_rate DESC) AS exclusion_cluster_rank
FROM geo_clusters
ORDER BY exclusion_rate DESC, respondent_count DESC
LIMIT 20;
"""

df_geographic_exclusion_clusters = pd.read_sql(query, engine)
df_geographic_exclusion_clusters

,latitude_band,longitude_band,dominant_region_sample,respondent_count,counties_in_cluster,avg_latitude,avg_longitude,excluded_respondents,exclusion_rate,exclusion_cluster_rank
0,1.5,35.0,Rift Valley,66,2,1.7347,35.2447,36,54.55,1
1,1.0,35.0,Rift Valley,405,3,1.2320,35.2564,147,36.30,2
2,-3.0,40.0,Coast,85,2,-2.7167,40.2024,29,34.12,3
3,-1.5,34.5,Nyanza,143,2,-1.1662,34.6715,44,30.77,4
4,-1.5,34.0,Nyanza,180,1,-1.1112,34.4450,55,30.56,5
5,-3.0,37.5,Eastern,60,2,-2.8181,37.6272,17,28.33,6
6,3.0,35.5,Rift Valley,131,1,3.1699,35.6127,37,28.24,7
7,0.0,34.0,Nyanza,683,4,0.2699,34.2913,187,27.38,8
8,-1.0,34.0,Nyanza,307,2,-0.7072,34.2996,84,27.36,9
9,0.5,40.5,North Eastern,55,1,0.7489,40.7631,15,27.27,10


The geographic clustering result highlights spatial concentrations of exclusion. In the validated output, the highest-exclusion grid cluster is in a Rift Valley latitude-longitude band, with an exclusion rate above `50%`.

The implication is that exclusion is not only a county-level issue; it can cluster within and across county boundaries, affecting agent network planning, mobile connectivity strategy, and last-mile service delivery.


### 5. County Scorecard Export

The exported scorecard creates a reusable evidence base for charts, dashboards, and further statistical analysis. It carries the county-level findings into the next phase of analysis.


In [39]:
# Scorecard export feeds Power BI, Python EDA, and written reporting.
export_path = OUTPUT_DIR / "finaccess_county_scorecard_2024.csv"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

df_final_county_scorecard.to_csv(export_path, index=False)

print(f"Exported {len(df_final_county_scorecard)} county records to {export_path}")


Exported 47 county records to C:\Portfolio\FinancialInclusion2024\outputs\finaccess_county_scorecard_2024.csv


The exported scorecard contains the 47-county scorecard with demographic context, financial access rates, exclusion measures, financial health scores, regional benchmarks, composite inclusion scores, and rankings. This file is the main bridge from the database analysis into dashboarding and Python EDA.


### 6. Executive Summary Tables

The summary tables present the top inclusion counties, highest-exclusion counties, national averages, gender gaps, and income gaps in a compact decision-ready format.


In [41]:
# Executive tables condense national, county, gender, and income findings for stakeholders.
summary_query = """
WITH national_averages AS (
    SELECT
        COUNT(*) AS total_respondents,
        ROUND((AVG(CASE WHEN mobile_money_use = 1 THEN 1.0 WHEN mobile_money_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS mobile_money_rate,
        ROUND((AVG(CASE WHEN bank_use = 1 THEN 1.0 WHEN bank_use IS NULL THEN NULL ELSE 0.0 END) * 100)::numeric, 2) AS bank_rate,
        ROUND((AVG(CASE WHEN "Savings_usage" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS savings_rate,
        ROUND((AVG(CASE WHEN "Loan_usage" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS loan_rate,
        ROUND((AVG(CASE WHEN "All_Insurance_including_NHIF" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS insurance_rate,
        ROUND((AVG(CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100)::numeric, 2) AS overall_access_rate,
        ROUND(AVG(finhealth_fnl)::numeric, 2) AS avg_finhealth_fnl,
        ROUND(AVG(vul_index_fnl)::numeric, 2) AS avg_vul_index_fnl,
        ROUND(AVG("Financial_literacy_index_fnl")::numeric, 2) AS avg_financial_literacy_index_fnl
    FROM finaccess_master
),
gender_stats AS (
    SELECT
        ROUND((AVG(CASE WHEN "Sex" = 1 THEN CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS male_overall_access_rate,
        ROUND((AVG(CASE WHEN "Sex" = 2 THEN CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) * 100)::numeric, 2) AS female_overall_access_rate,
        ROUND(((AVG(CASE WHEN "Sex" = 1 THEN CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END) - AVG(CASE WHEN "Sex" = 2 THEN CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END END)) * 100)::numeric, 2) AS national_overall_access_gender_gap,
        ROUND(((AVG(CASE WHEN "Sex" = 1 THEN CASE WHEN bank_use = 1 THEN 1.0 ELSE 0.0 END END) - AVG(CASE WHEN "Sex" = 2 THEN CASE WHEN bank_use = 1 THEN 1.0 ELSE 0.0 END END)) * 100)::numeric, 2) AS national_bank_gender_gap
    FROM finaccess_master
),
income_stats AS (
    SELECT
        ROUND((MAX(CASE WHEN "Quintiles" = 5 THEN overall_access_rate END) - MAX(CASE WHEN "Quintiles" = 1 THEN overall_access_rate END))::numeric, 2) AS q5_q1_overall_access_gap,
        ROUND((MAX(CASE WHEN "Quintiles" = 5 THEN bank_rate END) - MAX(CASE WHEN "Quintiles" = 1 THEN bank_rate END))::numeric, 2) AS q5_q1_bank_gap,
        ROUND((MAX(CASE WHEN "Quintiles" = 5 THEN avg_finhealth_fnl END) - MAX(CASE WHEN "Quintiles" = 1 THEN avg_finhealth_fnl END))::numeric, 2) AS q5_q1_finhealth_gap
    FROM (
        SELECT
            "Quintiles",
            AVG(CASE WHEN "Overall_Access_fnl" = 1 THEN 1.0 ELSE 0.0 END) * 100 AS overall_access_rate,
            AVG(CASE WHEN bank_use = 1 THEN 1.0 WHEN bank_use IS NULL THEN NULL ELSE 0.0 END) * 100 AS bank_rate,
            AVG(finhealth_fnl) AS avg_finhealth_fnl
        FROM finaccess_master
        WHERE "Quintiles" IS NOT NULL
        GROUP BY "Quintiles"
    ) q
)
SELECT 'National averages' AS summary_section, 'Total respondents' AS metric, total_respondents::text AS value FROM national_averages
UNION ALL SELECT 'National averages', 'Mobile money rate (%)', mobile_money_rate::text FROM national_averages
UNION ALL SELECT 'National averages', 'Bank rate (%)', bank_rate::text FROM national_averages
UNION ALL SELECT 'National averages', 'Savings rate (%)', savings_rate::text FROM national_averages
UNION ALL SELECT 'National averages', 'Loan rate (%)', loan_rate::text FROM national_averages
UNION ALL SELECT 'National averages', 'Insurance rate (%)', insurance_rate::text FROM national_averages
UNION ALL SELECT 'National averages', 'Overall access rate (%)', overall_access_rate::text FROM national_averages
UNION ALL SELECT 'National averages', 'Average financial health score', avg_finhealth_fnl::text FROM national_averages
UNION ALL SELECT 'National averages', 'Average vulnerability index', avg_vul_index_fnl::text FROM national_averages
UNION ALL SELECT 'National averages', 'Average financial literacy index', avg_financial_literacy_index_fnl::text FROM national_averages
UNION ALL SELECT 'Gender gap statistics', 'Male overall access rate (%)', male_overall_access_rate::text FROM gender_stats
UNION ALL SELECT 'Gender gap statistics', 'Female overall access rate (%)', female_overall_access_rate::text FROM gender_stats
UNION ALL SELECT 'Gender gap statistics', 'Overall access gender gap, male minus female (pp)', national_overall_access_gender_gap::text FROM gender_stats
UNION ALL SELECT 'Gender gap statistics', 'Bank gender gap, male minus female (pp)', national_bank_gender_gap::text FROM gender_stats
UNION ALL SELECT 'Income inequality statistics', 'Q5 minus Q1 overall access gap (pp)', q5_q1_overall_access_gap::text FROM income_stats
UNION ALL SELECT 'Income inequality statistics', 'Q5 minus Q1 bank access gap (pp)', q5_q1_bank_gap::text FROM income_stats
UNION ALL SELECT 'Income inequality statistics', 'Q5 minus Q1 financial health gap', q5_q1_finhealth_gap::text FROM income_stats;
"""

df_summary_metrics = pd.read_sql(text(summary_query), engine)

top5_included = df_final_county_scorecard.sort_values("composite_inclusion_score", ascending=False).head(5)
bottom5_excluded = df_final_county_scorecard.sort_values("exclusion_rate", ascending=False).head(5)

print("Top 5 most financially included counties")
display(top5_included[["composite_inclusion_rank", "county_name", "region", "composite_inclusion_score", "overall_access_rate", "bank_rate", "mobile_money_rate"]])

print("Bottom 5 most financially excluded counties")
display(bottom5_excluded[["county_name", "region", "excluded_respondents", "exclusion_rate", "overall_access_rate", "bank_rate", "mobile_money_rate"]])

print("National averages, gender gaps, and income inequality statistics")
display(df_summary_metrics)

Top 5 most financially included counties


,composite_inclusion_rank,county_name,region,composite_inclusion_score,overall_access_rate,bank_rate,mobile_money_rate
0,1,Nairobi,Nairobi,74.06,93.73,72.99,92.93
1,2,Kiambu,Central,71.45,89.65,66.98,86.11
2,3,Embu,Eastern,68.31,90.17,54.18,87.03
3,4,Nyeri,Central,66.88,92.12,59.30,89.93
4,5,Elgeyo-Marakwet,Rift Valley,66.51,85.92,53.99,83.80


Bottom 5 most financially excluded counties


,county_name,region,excluded_respondents,exclusion_rate,overall_access_rate,bank_rate,mobile_money_rate
45,West Pokot,Rift Valley,191,50.93,49.07,20.53,45.33
43,Turkana,Rift Valley,139,34.75,65.25,23.50,64.75
46,Tana River,Coast,97,29.13,70.87,23.12,70.27
38,Narok,Rift Valley,113,27.83,72.17,39.01,69.38
36,Migori,Nyanza,144,27.12,72.88,38.98,69.87


National averages, gender gaps, and income inequality statistics


,summary_section,metric,value
0,National averages,Total respondents,20871
1,National averages,Mobile money rate (%),78.69
2,National averages,Bank rate (%),45.52
3,National averages,Savings rate (%),63.45
4,National averages,Loan rate (%),61.21
5,National averages,Insurance rate (%),19.25
6,National averages,Overall access rate (%),81.43
7,National averages,Average financial health score,0.15
8,National averages,Average vulnerability index,2.45
9,National averages,Average financial literacy index,1.85


The formatted summary table presents the main story in a compact form. Nairobi, Kiambu, Embu, Nyeri, and Elgeyo-Marakwet lead on the composite inclusion score, while West Pokot, Turkana, Tana River, Narok, and Migori have the highest exclusion rates.

Nationally, the validated results show `78.69%` mobile money use, `45.52%` bank use, `63.45%` savings use, `61.21%` loan use, `19.25%` insurance use, and `81.43%` overall access. The overall gender gap is small, but the bank-use gender gap and income gradient remain important signals for targeted policy and product design.


### Analytical Conclusion

Kenya shows broad financial inclusion through mobile money, but formal banking, insurance, financial health, and resilience remain uneven. National mobile money use is high at `78.69%`, while bank use is `45.52%` and insurance use is `19.25%`. Overall access is `81.43%` under the working definition, but exclusion remains concentrated in counties such as West Pokot, Turkana, Tana River, Narok, and Migori.

Five findings stand out. First, mobile money is the strongest access channel but does not guarantee deeper financial resilience. Second, county differences remain large despite strong national access. Third, income is a major dividing line, with overall access rising from `68.57%` in the lowest quintile to `92.83%` in the highest. Fourth, national gender parity on overall access masks larger product-specific and county-level differences. Fifth, financial health and vulnerability should be analysed alongside access because usage alone does not measure household resilience.

Policy priorities should focus on high-exclusion counties, resilience-oriented products, and segmentation by geography, gender, and income. Fintechs should design low-cost mobile-first products for irregular-income users, use county-level rollout strategies, and treat financial literacy and trust as product design requirements.

The next phase uses Python to visualise county rankings, map exclusion patterns, apply survey weights, and develop evidence that can support dashboards, policy briefs, and product strategy.
